// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RequestAttribute,
} from './';

/**
 * @export
 * @interface AddRaProfileRequestDto
 */
export interface AddRaProfileRequestDto {
    /**
     * RA Profile name
     * @type {string}
     * @memberof AddRaProfileRequestDto
     */
    name: string;
    /**
     * RA Profile description
     * @type {string}
     * @memberof AddRaProfileRequestDto
     */
    description?: string;
    /**
     * List of Attributes to create RA Profile
     * @type {Array<RequestAttribute>}
     * @memberof AddRaProfileRequestDto
     */
    attributes: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof AddRaProfileRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * Enabled flag - true = enabled; false = disabled
     * @type {boolean}
     * @memberof AddRaProfileRequestDto
     */
    enabled?: boolean;
}
