// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SecretType,
} from './';

/**
 * Secret representing an API Key
 * @export
 * @interface ApiKeySecretContent
 */
export interface ApiKeySecretContent {
    /**
     * Secret type
     * @type {SecretType}
     * @memberof ApiKeySecretContent
     */
    type: SecretType;
    /**
     * API Key content encoded as Base64 string
     * @type {string}
     * @memberof ApiKeySecretContent
     */
    content: string;
}


