// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.8.2-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ApprovalStepRecipientDto } from "./";

/**
 * List of Approval steps related to this Approval
 * @export
 * @interface ApprovalDetailStepDto
 */
export interface ApprovalDetailStepDto {
    /**
     * Reference to responsible user to Approved the action
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    userUuid?: string;
    /**
     * Reference to responsible role of the users to Approved the action
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    roleUuid?: string;
    /**
     * Reference to responsible group of the users to Approved the action
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    groupUuid?: string;
    /**
     * Description of the Approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    description?: string;
    /**
     * Order of the position in the approval steps flow
     * @type {number}
     * @memberof ApprovalDetailStepDto
     */
    order: number;
    /**
     * Count of the required approvals for the Approval step, by default there is 1 approval needed.
     * @type {number}
     * @memberof ApprovalDetailStepDto
     */
    requiredApprovals?: number;
    /**
     * UUID of the Approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    approvalStepUuid: string;
    /**
     * List of the approval recipient related for this step
     * @type {Array<ApprovalStepRecipientDto>}
     * @memberof ApprovalDetailStepDto
     */
    approvalStepRecipients: Array<ApprovalStepRecipientDto>;
}
