// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.10.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ApprovalStepRecipientDto,
} from './';

/**
 * List of Approval steps related to this Approval
 * @export
 * @interface ApprovalDetailStepDto
 */
export interface ApprovalDetailStepDto {
    /**
     * UUID of the responsible user to approve action in approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    userUuid?: string;
    /**
     * UUID of the responsible role of the users to approve action in approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    roleUuid?: string;
    /**
     * UUID of the responsible group of the users to approve action in approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    groupUuid?: string;
    /**
     * Description of the approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    description?: string;
    /**
     * Order of the position in the approval steps flow
     * @type {number}
     * @memberof ApprovalDetailStepDto
     */
    order: number;
    /**
     * Count of the required approvals for the approval step, by default there is 1 approval needed.
     * @type {number}
     * @memberof ApprovalDetailStepDto
     */
    requiredApprovals?: number;
    /**
     * UUID of the Approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    uuid: string;
    /**
     * Username of the responsible user to approve action in approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    username?: string;
    /**
     * Name of the responsible role of the users to approve action in approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    roleName?: string;
    /**
     * Name of the responsible group of the users to approve action in approval step
     * @type {string}
     * @memberof ApprovalDetailStepDto
     */
    groupName?: string;
    /**
     * List of the approval recipient related for this step
     * @type {Array<ApprovalStepRecipientDto>}
     * @memberof ApprovalDetailStepDto
     */
    approvalStepRecipients: Array<ApprovalStepRecipientDto>;
}
