// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Type of the attribute content. 
 * @export
 * @enum {string}
 */
export enum AttributeContentType {
    String = 'string',
    Text = 'text',
    Integer = 'integer',
    Boolean = 'boolean',
    Float = 'float',
    Date = 'date',
    Time = 'time',
    Datetime = 'datetime',
    Secret = 'secret',
    File = 'file',
    Credential = 'credential',
    Codeblock = 'codeblock',
    Object = 'object'
}

