// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AuthenticationServiceExceptionDto
 */
export interface AuthenticationServiceExceptionDto {
    /**
     * Status code of the HTTP Request
     * @type {number}
     * @memberof AuthenticationServiceExceptionDto
     */
    statusCode: number;
    /**
     * Code of the result
     * @type {string}
     * @memberof AuthenticationServiceExceptionDto
     */
    code: string;
    /**
     * Exception message
     * @type {string}
     * @memberof AuthenticationServiceExceptionDto
     */
    message: string;
}
