// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.5.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    DateTimeAttributeConstraint,
    DateTimeAttributeConstraintData,
    RangeAttributeConstraint,
    RegexpAttributeConstraint,
} from './';

/**
 * Optional regular expressions and constraints used for validating the Attribute content
 * @export
 * @interface BaseAttributeConstraint
 */
export interface BaseAttributeConstraint {
    /**
     * Description of the constraint
     * @type {string}
     * @memberof BaseAttributeConstraint
     */
    description?: string;
    /**
     * Error message to be displayed for wrong data
     * @type {string}
     * @memberof BaseAttributeConstraint
     */
    errorMessage?: string;
    /**
     * Attribute Constraint Type
     * @type {string}
     * @memberof BaseAttributeConstraint
     */
    type: BaseAttributeConstraintTypeEnum;
    /**
     * Attribute Constraint Data
     * @type {object}
     * @memberof BaseAttributeConstraint
     */
    data: object;
}

/**
 * @export
 * @enum {string}
 */
export enum BaseAttributeConstraintTypeEnum {
    RegExp = 'regExp',
    Range = 'range',
    DateTime = 'dateTime'
}

