// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeCallback,
    AttributeContentType,
    AttributeType,
    BaseAttributeConstraint,
    BaseAttributeContentDtoV2,
    CustomAttributeProperties,
    CustomAttributeV2,
    DataAttributeV2,
    GroupAttributeV2,
    InfoAttributeV2,
    MetadataAttributeV2,
} from './';

/**
 * @type BaseAttributeDtoV2
 * Base Attribute definition
 * @export
 */
export type BaseAttributeDtoV2 = CustomAttributeV2 | DataAttributeV2 | GroupAttributeV2 | InfoAttributeV2 | MetadataAttributeV2;
