// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    BooleanAttributeContentV2,
    CodeBlockAttributeContentV2,
    CredentialAttributeContentV2,
    DateAttributeContentV2,
    DateTimeAttributeContentV2,
    FileAttributeContentV2,
    FloatAttributeContentV2,
    IntegerAttributeContentV2,
    ObjectAttributeContentV2,
    SecretAttributeContentV2,
    StringAttributeContentV2,
    TextAttributeContentV2,
    TimeAttributeContentV2,
} from './';

/**
 * @type BaseAttributeContentDtoV2
 * Base Attribute ContentV2 definition
 * @export
 */
export type BaseAttributeContentDtoV2 = BooleanAttributeContentV2 | CodeBlockAttributeContentV2 | CredentialAttributeContentV2 | DateAttributeContentV2 | DateTimeAttributeContentV2 | FileAttributeContentV2 | FloatAttributeContentV2 | IntegerAttributeContentV2 | ObjectAttributeContentV2 | SecretAttributeContentV2 | StringAttributeContentV2 | TextAttributeContentV2 | TimeAttributeContentV2;
