// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CbomDto
 */
export interface CbomDto {
    /**
     * UUID of a CBOM record
     * @type {string}
     * @memberof CbomDto
     */
    uuid: string;
    /**
     * Creation timestamp of CBOM database record
     * @type {string}
     * @memberof CbomDto
     */
    createdAt: string;
    /**
     * CBOM serial number (URN)
     * @type {string}
     * @memberof CbomDto
     */
    serialNumber: string;
    /**
     * CBOM version
     * @type {number}
     * @memberof CbomDto
     */
    version: number;
    /**
     * CBOM spec version
     * @type {string}
     * @memberof CbomDto
     */
    specVersion: string;
    /**
     * A timestamp from CBOM metadata
     * @type {string}
     * @memberof CbomDto
     */
    timestamp: string;
    /**
     * CBOM source (e.g.: CBOM-Lens)
     * @type {string}
     * @memberof CbomDto
     */
    source: string;
    /**
     * Number of algorithms
     * @type {number}
     * @memberof CbomDto
     */
    algorithms: number;
    /**
     * Number of certificates
     * @type {number}
     * @memberof CbomDto
     */
    certificates: number;
    /**
     * Number of protocols
     * @type {number}
     * @memberof CbomDto
     */
    protocols: number;
    /**
     * Number of crypto material items
     * @type {number}
     * @memberof CbomDto
     */
    cryptoMaterial: number;
    /**
     * Total number of assets
     * @type {number}
     * @memberof CbomDto
     */
    totalAssets: number;
}
