// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SearchFilterRequestDto,
} from './';

/**
 * @export
 * @interface CertificateSearchRequestDto
 */
export interface CertificateSearchRequestDto {
    /**
     * Certificate filter input
     * @type {Array<SearchFilterRequestDto>}
     * @memberof CertificateSearchRequestDto
     */
    filters?: Array<SearchFilterRequestDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof CertificateSearchRequestDto
     */
    itemsPerPage?: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof CertificateSearchRequestDto
     */
    pageNumber?: number;
    /**
     * Include archived certificates
     * @type {boolean}
     * @memberof CertificateSearchRequestDto
     */
    includeArchived?: boolean;
}
