// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.9.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CertificateChainDownloadResponseDto
 */
export interface CertificateChainDownloadResponseDto {
    /**
     * Indicator whether the chain returned is complete
     * @type {boolean}
     * @memberof CertificateChainDownloadResponseDto
     */
    completeChain: boolean;
    /**
     * Format of the downloaded chain
     * @type {string}
     * @memberof CertificateChainDownloadResponseDto
     */
    format: CertificateChainDownloadResponseDtoFormatEnum;
    /**
     * Base64 encoded certificate chain in the specified format
     * @type {string}
     * @memberof CertificateChainDownloadResponseDto
     */
    content: string;
}

/**
 * @export
 * @enum {string}
 */
export enum CertificateChainDownloadResponseDtoFormatEnum {
    Pkcs7 = "pkcs7",
    Pem = "pem",
}
