// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CertificateState,
    CertificateValidationStatus,
    MetadataResponseDto,
    ResponseAttribute,
} from './';

/**
 * @export
 * @interface CertificateInLocationDto
 */
export interface CertificateInLocationDto {
    /**
     * UUID of the Certificate
     * @type {string}
     * @memberof CertificateInLocationDto
     */
    certificateUuid: string;
    /**
     * State of the Certificate
     * @type {CertificateState}
     * @memberof CertificateInLocationDto
     */
    state: CertificateState;
    /**
     * Current validation status of the certificate
     * @type {CertificateValidationStatus}
     * @memberof CertificateInLocationDto
     */
    validationStatus: CertificateValidationStatus;
    /**
     * Common Name of the Subject DN field of the Certificate
     * @type {string}
     * @memberof CertificateInLocationDto
     */
    commonName: string;
    /**
     * Serial number in HEX of the Certificate
     * @type {string}
     * @memberof CertificateInLocationDto
     */
    serialNumber: string;
    /**
     * Metadata of the Certificate in Location
     * @type {Array<MetadataResponseDto>}
     * @memberof CertificateInLocationDto
     */
    metadata?: Array<MetadataResponseDto>;
    /**
     * Applied push attributes
     * @type {Array<ResponseAttribute>}
     * @memberof CertificateInLocationDto
     */
    pushAttributes?: Array<ResponseAttribute>;
    /**
     * Applied issue attributes
     * @type {Array<ResponseAttribute>}
     * @memberof CertificateInLocationDto
     */
    csrAttributes?: Array<ResponseAttribute>;
    /**
     * If the Certificate in Location has associated private key
     * @type {boolean}
     * @memberof CertificateInLocationDto
     */
    withKey?: boolean;
}


