// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.10.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CertificateComplianceResultDto,
    CertificateDto,
    CertificateRequestDto,
    CertificateState,
    CertificateType,
    CertificateValidationStatus,
    ComplianceStatus,
    GroupDto,
    KeyDto,
    LocationDto,
    MetadataResponseDto,
    ResponseAttributeDto,
    SimplifiedRaProfileDto,
} from "./";

/**
 * @export
 * @interface CertificateDetailDto
 */
export interface CertificateDetailDto {
    /**
     * UUID of the Certificate
     * @type {string}
     * @memberof CertificateDetailDto
     */
    uuid: string;
    /**
     * Certificate common name
     * @type {string}
     * @memberof CertificateDetailDto
     */
    commonName: string;
    /**
     * Certificate serial number
     * @type {string}
     * @memberof CertificateDetailDto
     */
    serialNumber?: string;
    /**
     * Certificate issuer common name
     * @type {string}
     * @memberof CertificateDetailDto
     */
    issuerCommonName?: string;
    /**
     * Issuer DN of the Certificate
     * @type {string}
     * @memberof CertificateDetailDto
     */
    issuerDn?: string;
    /**
     * Subject DN of the Certificate
     * @type {string}
     * @memberof CertificateDetailDto
     */
    subjectDn: string;
    /**
     * Certificate validity start date
     * @type {string}
     * @memberof CertificateDetailDto
     */
    notBefore?: string;
    /**
     * Certificate expiration date
     * @type {string}
     * @memberof CertificateDetailDto
     */
    notAfter?: string;
    /**
     * Public key algorithm
     * @type {string}
     * @memberof CertificateDetailDto
     */
    publicKeyAlgorithm: string;
    /**
     * Certificate signature algorithm
     * @type {string}
     * @memberof CertificateDetailDto
     */
    signatureAlgorithm: string;
    /**
     * Certificate key size
     * @type {number}
     * @memberof CertificateDetailDto
     */
    keySize: number;
    /**
     * @type {CertificateState}
     * @memberof CertificateDetailDto
     */
    state: CertificateState;
    /**
     * @type {CertificateValidationStatus}
     * @memberof CertificateDetailDto
     */
    validationStatus: CertificateValidationStatus;
    /**
     * @type {SimplifiedRaProfileDto}
     * @memberof CertificateDetailDto
     */
    raProfile?: SimplifiedRaProfileDto;
    /**
     * SHA256 fingerprint of the Certificate
     * @type {string}
     * @memberof CertificateDetailDto
     */
    fingerprint?: string;
    /**
     * @type {GroupDto}
     * @memberof CertificateDetailDto
     */
    group?: GroupDto;
    /**
     * Certificate Owner
     * @type {string}
     * @memberof CertificateDetailDto
     */
    owner?: string;
    /**
     * Certificate Owner UUID
     * @type {string}
     * @memberof CertificateDetailDto
     */
    ownerUuid?: string;
    /**
     * @type {CertificateType}
     * @memberof CertificateDetailDto
     */
    certificateType?: CertificateType;
    /**
     * Serial number of the issuer
     * @type {string}
     * @memberof CertificateDetailDto
     */
    issuerSerialNumber?: string;
    /**
     * @type {ComplianceStatus}
     * @memberof CertificateDetailDto
     */
    complianceStatus?: ComplianceStatus;
    /**
     * UUID of the issuer certificate
     * @type {string}
     * @memberof CertificateDetailDto
     */
    issuerCertificateUuid?: string;
    /**
     * Private Key Availability
     * @type {boolean}
     * @memberof CertificateDetailDto
     */
    privateKeyAvailability: boolean;
    /**
     * Indicator whether CA is marked as trusted, set to null if certificate is not CA
     * @type {boolean}
     * @memberof CertificateDetailDto
     */
    trustedCa: boolean;
    /**
     * Extended key usages
     * @type {Array<string>}
     * @memberof CertificateDetailDto
     */
    extendedKeyUsage?: Array<string>;
    /**
     * Key usages
     * @type {Array<string>}
     * @memberof CertificateDetailDto
     */
    keyUsage: Array<string>;
    /**
     * Basic Constraints
     * @type {string}
     * @memberof CertificateDetailDto
     */
    basicConstraints: string;
    /**
     * Certificate metadata
     * @type {Array<MetadataResponseDto>}
     * @memberof CertificateDetailDto
     */
    metadata?: Array<MetadataResponseDto>;
    /**
     * Base64 encoded Certificate content
     * @type {string}
     * @memberof CertificateDetailDto
     */
    certificateContent: string;
    /**
     * Subject alternative names
     * @type {{ [key: string]: object; }}
     * @memberof CertificateDetailDto
     */
    subjectAlternativeNames?: { [key: string]: object };
    /**
     * Locations associated to the Certificate
     * @type {Array<LocationDto>}
     * @memberof CertificateDetailDto
     */
    locations?: Array<LocationDto>;
    /**
     * Certificate compliance check result
     * @type {Array<CertificateComplianceResultDto>}
     * @memberof CertificateDetailDto
     */
    nonCompliantRules?: Array<CertificateComplianceResultDto>;
    /**
     * List of Custom Attributes
     * @type {Array<ResponseAttributeDto>}
     * @memberof CertificateDetailDto
     */
    customAttributes?: Array<ResponseAttributeDto>;
    /**
     * @type {KeyDto}
     * @memberof CertificateDetailDto
     */
    key?: KeyDto;
    /**
     * @type {CertificateRequestDto}
     * @memberof CertificateDetailDto
     */
    certificateRequest?: CertificateRequestDto;
    /**
     * Source certificate UUID
     * @type {string}
     * @memberof CertificateDetailDto
     */
    sourceCertificateUuid?: string;
    /**
     * List of issue attributes
     * @type {Array<ResponseAttributeDto>}
     * @memberof CertificateDetailDto
     */
    issueAttributes?: Array<ResponseAttributeDto>;
    /**
     * List of revoke attributes
     * @type {Array<ResponseAttributeDto>}
     * @memberof CertificateDetailDto
     */
    revokeAttributes?: Array<ResponseAttributeDto>;
    /**
     * List of related certificates
     * @type {Array<CertificateDto>}
     * @memberof CertificateDetailDto
     */
    relatedCertificates?: Array<CertificateDto>;
}
