// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.14.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CertificateValidationSettingsUpdateDto
 */
export interface CertificateValidationSettingsUpdateDto {
    /**
     * Indicator whether validation of certificates should be enabled
     * @type {boolean}
     * @memberof CertificateValidationSettingsUpdateDto
     */
    enabled: boolean;
    /**
     * Frequency of validation of certificates in days
     * @type {number}
     * @memberof CertificateValidationSettingsUpdateDto
     */
    frequency?: number;
    /**
     * How many days before expiration should certificate validation status change to Expiring
     * @type {number}
     * @memberof CertificateValidationSettingsUpdateDto
     */
    expiringThreshold?: number;
}
