// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * Token profile and naming for key material imported with a certificate
 * @export
 * @interface CertificateEntryKeyDestinationDto
 */
export interface CertificateEntryKeyDestinationDto {
    /**
     * Token profile that will hold the imported key material
     * @type {string}
     * @memberof CertificateEntryKeyDestinationDto
     */
    tokenProfileUuid: string;
    /**
     * Name for the imported key. The platform derives one from the certificate when this is absent.
     * @type {string}
     * @memberof CertificateEntryKeyDestinationDto
     */
    keyName?: string;
    /**
     * Whether the imported key may later be exported. Defaults to false, and false is final. It can only be requested where the token profile reports key export as available for the key type.
     * @type {boolean}
     * @memberof CertificateEntryKeyDestinationDto
     */
    exportable?: boolean;
    /**
     * Attributes required by the provider to import a key, from the import attribute schema
     * @type {Array<RequestAttribute>}
     * @memberof CertificateEntryKeyDestinationDto
     */
    importAttributes?: Array<RequestAttribute>;
    /**
     * Custom attributes for the imported key. A key that arrives inside a container carries the same custom attributes as one imported on its own.
     * @type {Array<RequestAttribute>}
     * @memberof CertificateEntryKeyDestinationDto
     */
    customAttributes?: Array<RequestAttribute>;
}
