// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.8.2-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttributeDto } from "./";

/**
 * @export
 * @interface ClientCertificateRequestDto
 */
export interface ClientCertificateRequestDto {
    /**
     * RA Profile UUID. Required if CSR is not uploaded
     * @type {string}
     * @memberof ClientCertificateRequestDto
     */
    raProfileUuid: string;
    /**
     * Source certificate UUID to specify in case of renew/rekey operation
     * @type {string}
     * @memberof ClientCertificateRequestDto
     */
    sourceCertificateUuid?: string;
    /**
     * List of attributes to create CSR. Required if CSR is not provided
     * @type {Array<RequestAttributeDto>}
     * @memberof ClientCertificateRequestDto
     */
    csrAttributes?: Array<RequestAttributeDto>;
    /**
     * List of attributes to sign the CSR
     * @type {Array<RequestAttributeDto>}
     * @memberof ClientCertificateRequestDto
     */
    signatureAttributes?: Array<RequestAttributeDto>;
    /**
     * Certificate sign request (PKCS#10) encoded as Base64 string
     * @type {string}
     * @memberof ClientCertificateRequestDto
     */
    pkcs10?: string;
    /**
     * Token Profile UUID. Required if CSR is not uploaded
     * @type {string}
     * @memberof ClientCertificateRequestDto
     */
    tokenProfileUuid?: string;
    /**
     * Key UUID. Required if CSR is not uploaded
     * @type {string}
     * @memberof ClientCertificateRequestDto
     */
    keyUuid?: string;
    /**
     * List of RA Profile related Attributes to issue Certificate
     * @type {Array<RequestAttributeDto>}
     * @memberof ClientCertificateRequestDto
     */
    issueAttributes: Array<RequestAttributeDto>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttributeDto>}
     * @memberof ClientCertificateRequestDto
     */
    customAttributes?: Array<RequestAttributeDto>;
}
