// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.5.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    EndEntityExtendedInfoDto,
    RaProfileDto,
} from './';

/**
 * @export
 * @interface ClientEditEndEntityRequestDto
 */
export interface ClientEditEndEntityRequestDto {
    /**
     * @type {RaProfileDto}
     * @memberof ClientEditEndEntityRequestDto
     */
    raProfile: RaProfileDto;
    /**
     * End Entity email
     * @type {string}
     * @memberof ClientEditEndEntityRequestDto
     */
    email?: string;
    /**
     * End Entity extension data
     * @type {Array<EndEntityExtendedInfoDto>}
     * @memberof ClientEditEndEntityRequestDto
     */
    extensionData?: Array<EndEntityExtendedInfoDto>;
    /**
     * End Entity password
     * @type {string}
     * @memberof ClientEditEndEntityRequestDto
     */
    password: string;
    /**
     * End Entity Subject alternative name
     * @type {string}
     * @memberof ClientEditEndEntityRequestDto
     */
    subjectAltName?: string;
    /**
     * End Entity subject domain name
     * @type {string}
     * @memberof ClientEditEndEntityRequestDto
     */
    subjectDN: string;
    /**
     * End Entity Subject domain name
     * @type {string}
     * @memberof ClientEditEndEntityRequestDto
     */
    status: ClientEditEndEntityRequestDtoStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ClientEditEndEntityRequestDtoStatusEnum {
    New = 'NEW',
    Failed = 'FAILED',
    Initialized = 'INITIALIZED',
    InProcess = 'IN_PROCESS',
    Generated = 'GENERATED',
    Revoked = 'REVOKED',
    Historical = 'HISTORICAL',
    KeyRecovery = 'KEY_RECOVERY',
    WaitingForAddApproval = 'WAITING_FOR_ADD_APPROVAL'
}

