// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProtectionMethod,
    RequestAttributeDto,
} from './';

/**
 * @export
 * @interface CmpProfileEditRequestDto
 */
export interface CmpProfileEditRequestDto {
    /**
     * Description of the CMP Profile
     * @type {string}
     * @memberof CmpProfileEditRequestDto
     */
    description?: string;
    /**
     * RA Profile UUID that the CMP Profile is associated with
     * @type {string}
     * @memberof CmpProfileEditRequestDto
     */
    raProfileUuid?: string;
    /**
     * List of Attributes to issue Certificate for the associated RA Profile. Required when raProfileUuid is provided
     * @type {Array<RequestAttributeDto>}
     * @memberof CmpProfileEditRequestDto
     */
    issueCertificateAttributes?: Array<RequestAttributeDto>;
    /**
     * List of Attributes to revoke Certificate for the associated RA Profile. Required when raProfileUuid is provided
     * @type {Array<RequestAttributeDto>}
     * @memberof CmpProfileEditRequestDto
     */
    revokeCertificateAttributes?: Array<RequestAttributeDto>;
    /**
     * List of Custom Attributes for CMP Profile
     * @type {Array<RequestAttributeDto>}
     * @memberof CmpProfileEditRequestDto
     */
    customAttributes?: Array<RequestAttributeDto>;
    /**
     * @type {ProtectionMethod}
     * @memberof CmpProfileEditRequestDto
     */
    requestProtectionMethod: ProtectionMethod;
    /**
     * @type {ProtectionMethod}
     * @memberof CmpProfileEditRequestDto
     */
    responseProtectionMethod: ProtectionMethod;
    /**
     * Shared secret for the CMP Request. Required when requestProtectionMethod is sharedSecret
     * @type {string}
     * @memberof CmpProfileEditRequestDto
     */
    sharedSecret?: string;
    /**
     * UUID of the Certificate to be used as signing certificate for CMP responses. Required when responseProtectionMethod is signature
     * @type {string}
     * @memberof CmpProfileEditRequestDto
     */
    signingCertificateUuid?: string;
    /**
     * Name of the CMP Profile
     * @type {string}
     * @memberof CmpProfileEditRequestDto
     */
    name: string;
}


