// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.10.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ComplianceRulesDto } from './';

/**
 * List of rules
 * @export
 * @interface ComplianceConnectorAndRulesDto
 */
export interface ComplianceConnectorAndRulesDto {
    /**
     * Name of the Compliance Provider
     * @type {string}
     * @memberof ComplianceConnectorAndRulesDto
     */
    connectorName?: string;
    /**
     * UUID of the Compliance Provider
     * @type {string}
     * @memberof ComplianceConnectorAndRulesDto
     */
    connectorUuid?: string;
    /**
     * Kind of the Compliance Provider
     * @type {string}
     * @memberof ComplianceConnectorAndRulesDto
     */
    kind?: string;
    /**
     * Rules associated
     * @type {Array<ComplianceRulesDto>}
     * @memberof ComplianceConnectorAndRulesDto
     */
    rules?: Array<ComplianceRulesDto>;
}
