// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ProviderComplianceRulesRequestDto,
    RequestAttribute,
} from './';

/**
 * @export
 * @interface ComplianceProfileRequestDtoV2
 */
export interface ComplianceProfileRequestDtoV2 {
    /**
     * Description of the Compliance Profile
     * @type {string}
     * @memberof ComplianceProfileRequestDtoV2
     */
    description?: string;
    /**
     * UUIDs of internal rules to be associated with the Compliance Profile. Profiles can be created without rules and can be added later.
     * @type {Array<string>}
     * @memberof ComplianceProfileRequestDtoV2
     */
    internalRules?: Array<string>;
    /**
     * Provider rules to be associated with the Compliance Profile. Profiles can be created without rules and can be added later.
     * @type {Array<ProviderComplianceRulesRequestDto>}
     * @memberof ComplianceProfileRequestDtoV2
     */
    providerRules?: Array<ProviderComplianceRulesRequestDto>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof ComplianceProfileRequestDtoV2
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * Name of the Compliance Profile
     * @type {string}
     * @memberof ComplianceProfileRequestDtoV2
     */
    name: string;
}
