// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.1
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ConditionItemDto,
    ConditionType,
    Resource,
} from './';

/**
 * @export
 * @interface ConditionDto
 */
export interface ConditionDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof ConditionDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof ConditionDto
     */
    name: string;
    /**
     * Description of the condition
     * @type {string}
     * @memberof ConditionDto
     */
    description?: string;
    /**
     * Type of the condition
     * @type {ConditionType}
     * @memberof ConditionDto
     */
    type: ConditionType;
    /**
     * Resource associated with the condition
     * @type {Resource}
     * @memberof ConditionDto
     */
    resource: Resource;
    /**
     * List of the condition items
     * @type {Array<ConditionItemDto>}
     * @memberof ConditionDto
     */
    items: Array<ConditionItemDto>;
}


