// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.5.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RequestAttributeDto,
} from './';

/**
 * @export
 * @interface ConnectorRequestDto
 */
export interface ConnectorRequestDto {
    /**
     * Name of the Connector
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    name: string;
    /**
     * URL of the Connector to connect
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    url: string;
    /**
     * Type of authentication for the Connector
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    authType: ConnectorRequestDtoAuthTypeEnum;
    /**
     * List of authentication Attributes. Required if the authentication type is not NONE
     * @type {Array<RequestAttributeDto>}
     * @memberof ConnectorRequestDto
     */
    authAttributes?: Array<RequestAttributeDto>;
}

/**
 * @export
 * @enum {string}
 */
export enum ConnectorRequestDtoAuthTypeEnum {
    None = 'none',
    Basic = 'basic',
    Certificate = 'certificate',
    ApiKey = 'apiKey',
    Jwt = 'jwt'
}

