// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.15.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AuthType,
    RequestAttributeDto,
} from './';

/**
 * @export
 * @interface ConnectorRequestDto
 */
export interface ConnectorRequestDto {
    /**
     * Name of the Connector
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    name: string;
    /**
     * URL of the Connector to connect
     * @type {string}
     * @memberof ConnectorRequestDto
     */
    url: string;
    /**
     * Type of authentication for the Connector
     * @type {AuthType}
     * @memberof ConnectorRequestDto
     */
    authType: AuthType;
    /**
     * List of authentication Attributes. Required if the authentication type is not NONE
     * @type {Array<RequestAttributeDto>}
     * @memberof ConnectorRequestDto
     */
    authAttributes?: Array<RequestAttributeDto>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttributeDto>}
     * @memberof ConnectorRequestDto
     */
    customAttributes?: Array<RequestAttributeDto>;
}


