// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.8.2-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Status of the Connector
 * @export
 * @enum {string}
 */
export enum ConnectorStatus {
    WaitingForApproval = "waitingForApproval",
    Connected = "connected",
    Failed = "failed",
    Offline = "offline",
}
