// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.15.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RdnAttributeTypeOidPropertiesDto,
} from './';

/**
 * @type CustomOidEntryUpdateRequestDtoAdditionalProperties
 * Additional properties depending on OID category
 * @export
 */
export type CustomOidEntryUpdateRequestDtoAdditionalProperties = RdnAttributeTypeOidPropertiesDto;
