// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CustomOidEntryUpdateRequestDtoAdditionalProperties,
    OidCategory,
} from './';

/**
 * @export
 * @interface CustomOidEntryRequestDto
 */
export interface CustomOidEntryRequestDto {
    /**
     * Display name of the custom OID entry
     * @type {string}
     * @memberof CustomOidEntryRequestDto
     */
    displayName: string;
    /**
     * Description of the custom OID entry
     * @type {string}
     * @memberof CustomOidEntryRequestDto
     */
    description?: string;
    /**
     * Category of the OID entry. When updating OID entry, this property does not change the category and is instead used to determine type of additional properties.
     * @type {OidCategory}
     * @memberof CustomOidEntryRequestDto
     */
    category: OidCategory;
    /**
     * @type {CustomOidEntryUpdateRequestDtoAdditionalProperties}
     * @memberof CustomOidEntryRequestDto
     */
    additionalProperties?: CustomOidEntryUpdateRequestDtoAdditionalProperties;
    /**
     * Object Identifier (OID) in dot notation (e.g., 1.2.840.113549.1.1.1)
     * @type {string}
     * @memberof CustomOidEntryRequestDto
     */
    oid: string;
}


