// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeContentDtoV3,
    CustomAttributeProperties,
    CustomAttributeV2,
    CustomAttributeV3,
} from './';

/**
 * @type CustomAttribute
 * Custom Attribute
 * @export
 */
export type CustomAttribute = CustomAttributeV2 | CustomAttributeV3;
