// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    BaseAttributeContentDtoV3,
    CustomAttributeProperties,
    CustomAttributeV2,
    CustomAttributeV3,
} from './';

/**
 * @type CustomAttributeDto
 * Custom Attribute
 * @export
 */
export type CustomAttributeDto = CustomAttributeV2 | CustomAttributeV3;
