// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeCallback,
    AttributeContentType,
    AttributeType,
    BaseAttributeConstraintDto,
    BaseAttributeContentDtoV2,
    DataAttributeProperties,
} from './';

/**
 * Data attribute allows to store and transfer dynamic data. Its content can be edited and send in requests to store.
 * @export
 * @interface DataAttributeV2
 */
export interface DataAttributeV2 {
    /**
     * UUID of the Attribute for unique identification
     * @type {string}
     * @memberof DataAttributeV2
     */
    uuid: string;
    /**
     * Name of the Attribute that is used for identification
     * @type {string}
     * @memberof DataAttributeV2
     */
    name: string;
    /**
     * Optional description of the Attribute, should contain helper text on what is expected
     * @type {string}
     * @memberof DataAttributeV2
     */
    description?: string;
    /**
     * Version of the attribute
     * @type {number}
     * @memberof DataAttributeV2
     */
    version: number;
    /**
     * Type of the Attribute
     * @type {AttributeType}
     * @memberof DataAttributeV2
     */
    type: AttributeType;
    /**
     * Content of the Attribute
     * @type {Array<BaseAttributeContentDtoV2>}
     * @memberof DataAttributeV2
     */
    content?: Array<BaseAttributeContentDtoV2>;
    /**
     * Type of the Content
     * @type {AttributeContentType}
     * @memberof DataAttributeV2
     */
    contentType: AttributeContentType;
    /**
     * Properties of the Attributes
     * @type {DataAttributeProperties}
     * @memberof DataAttributeV2
     */
    properties: DataAttributeProperties;
    /**
     * Optional constraints used for validating the Attribute content
     * @type {Array<BaseAttributeConstraintDto>}
     * @memberof DataAttributeV2
     */
    constraints?: Array<BaseAttributeConstraintDto>;
    /**
     * Optional definition of callback for getting the content of the Attribute based on the action
     * @type {AttributeCallback}
     * @memberof DataAttributeV2
     */
    attributeCallback?: AttributeCallback;
}


