// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
} from './';

/**
 * DateTime attribute content in predefined format with timezone
 * @export
 * @interface DateTimeAttributeContentV3
 */
export interface DateTimeAttributeContentV3 {
    /**
     * Content Reference
     * @type {string}
     * @memberof DateTimeAttributeContentV3
     */
    reference?: string;
    /**
     * DateTime attribute value in format yyyy-MM-ddTHH:mm:ss.SSSXXX
     * @type {string}
     * @memberof DateTimeAttributeContentV3
     */
    data: string;
    /**
     * Content Type of the attribute
     * @type {AttributeContentType}
     * @memberof DateTimeAttributeContentV3
     */
    contentType: AttributeContentType;
}


