// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DigestAlgorithm {
    Md5 = 'MD5',
    Sha1 = 'SHA-1',
    Sha224 = 'SHA-224',
    Sha256 = 'SHA-256',
    Sha384 = 'SHA-384',
    Sha512 = 'SHA-512',
    Sha3256 = 'SHA3-256',
    Sha3384 = 'SHA3-384',
    Sha3512 = 'SHA3-512'
}

