// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    SigningProfileListDto,
} from './';

/**
 * Digital Signature details for listing
 * @export
 * @interface DigitalSignatureListDto
 */
export interface DigitalSignatureListDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof DigitalSignatureListDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof DigitalSignatureListDto
     */
    name: string;
    /**
     * Signing Profile used to produce this Digital Signature
     * @type {SigningProfileListDto}
     * @memberof DigitalSignatureListDto
     */
    signingProfile: SigningProfileListDto;
    /**
     * Claimed signing time embedded in the signature structure by the signing operation. This is the local time reported by the signer and may not be trusted unless corroborated by a timestamp token (see signingProtocol).
     * @type {string}
     * @memberof DigitalSignatureListDto
     */
    signingTime: string;
    /**
     * Server time at which the Digital Signature record was created in the system. This timestamp is set by the platform and is independent of the cryptographic signing time.
     * @type {string}
     * @memberof DigitalSignatureListDto
     */
    createdAt: string;
}
