// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.11.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RequestAttributeDto,
} from './';

/**
 * @export
 * @interface EditLocationRequestDto
 */
export interface EditLocationRequestDto {
    /**
     * Description of the Location
     * @type {string}
     * @memberof EditLocationRequestDto
     */
    description?: string;
    /**
     * List of Attributes for Location
     * @type {Array<RequestAttributeDto>}
     * @memberof EditLocationRequestDto
     */
    attributes: Array<RequestAttributeDto>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttributeDto>}
     * @memberof EditLocationRequestDto
     */
    customAttributes?: Array<RequestAttributeDto>;
    /**
     * Enabled flag - true = enabled; false = disabled
     * @type {boolean}
     * @memberof EditLocationRequestDto
     */
    enabled?: boolean;
}
