// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    FilterFieldSource,
} from './';

/**
 * List of the execution items to add to execution
 * @export
 * @interface ExecutionItemRequestDto
 */
export interface ExecutionItemRequestDto {
    /**
     * @type {FilterFieldSource}
     * @memberof ExecutionItemRequestDto
     */
    fieldSource: FilterFieldSource;
    /**
     * Field identifier of the execution item
     * @type {string}
     * @memberof ExecutionItemRequestDto
     */
    fieldIdentifier: string;
    /**
     * Data of the execution item
     * @type {object}
     * @memberof ExecutionItemRequestDto
     */
    data?: object;
}


