// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Type of the field
 * @export
 * @enum {string}
 */
export enum FilterFieldType {
    String = 'string',
    Number = 'number',
    List = 'list',
    Date = 'date',
    Datetime = 'datetime',
    Boolean = 'boolean'
}

