// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.0
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SecretType } from './';

/**
 * Secret representing generic content represented as string
 * @export
 * @interface GenericSecretContent
 */
export interface GenericSecretContent {
    /**
     * Secret type
     * @type {SecretType}
     * @memberof GenericSecretContent
     */
    type: SecretType;
    /**
     * Generic secret content represented as string. In case secret content is binary data, it should be encoded as BASE64 string.
     * @type {string}
     * @memberof GenericSecretContent
     */
    content: string;
}
