// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.5.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GroupRequestDto
 */
export interface GroupRequestDto {
    /**
     * Name of the Certificate Group
     * @type {string}
     * @memberof GroupRequestDto
     */
    name: string;
    /**
     * Description of the Certificate Group
     * @type {string}
     * @memberof GroupRequestDto
     */
    description?: string;
}
