// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimestampSourceType } from './';

/**
 * Timestamp source referencing a Timestamping Signing Profile on this platform by UUID, as supplied on create and update
 * @export
 * @interface InternalTimestampSourceRequestDto
 */
export interface InternalTimestampSourceRequestDto {
    /**
     * UUID of the Timestamping Signing Profile that issues the timestamps. ILM rejects a UUID that is not a Timestamping profile.
     * @type {string}
     * @memberof InternalTimestampSourceRequestDto
     */
    signingProfileUuid: string;
    /**
     * Kind of timestamp source, and the discriminator selecting the fields that accompany it
     * @type {TimestampSourceType}
     * @memberof InternalTimestampSourceRequestDto
     */
    type: TimestampSourceType;
}
