// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
} from './';

/**
 * Integer attribute content for integer numbers
 * @export
 * @interface IntegerAttributeContentV3
 */
export interface IntegerAttributeContentV3 {
    /**
     * Content Reference
     * @type {string}
     * @memberof IntegerAttributeContentV3
     */
    reference?: string;
    /**
     * Integer attribute value
     * @type {number}
     * @memberof IntegerAttributeContentV3
     */
    data: number;
    /**
     * Content Type of the attribute
     * @type {AttributeContentType}
     * @memberof IntegerAttributeContentV3
     */
    contentType: AttributeContentType;
}


