// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Integer attribute content for integer numbers
 * @export
 * @interface IntegerAttributeContentV2
 */
export interface IntegerAttributeContentV2 {
    /**
     * ContentV2 Reference
     * @type {string}
     * @memberof IntegerAttributeContentV2
     */
    reference?: string;
    /**
     * Integer attribute value
     * @type {number}
     * @memberof IntegerAttributeContentV2
     */
    data: number;
}
