// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface JwkDto
 */
export interface JwkDto {
    /**
     * The key ID parameter used to match a specific key in provider
     * @type {string}
     * @memberof JwkDto
     */
    kid: string;
    /**
     * Base64 encoded value of public key
     * @type {string}
     * @memberof JwkDto
     */
    publicKey: string;
    /**
     * The cryptographic algorithm family used with the key, such as \"RSA\" or \"EC\"
     * @type {string}
     * @memberof JwkDto
     */
    keyType?: string;
    /**
     * The algorithm intended for use with the key
     * @type {string}
     * @memberof JwkDto
     */
    algorithm?: string;
    /**
     * The intended use of the public key
     * @type {string}
     * @memberof JwkDto
     */
    use?: string;
}
