// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * Passphrase and provider options for exporting a key
 * @export
 * @interface KeyExportRequestDto
 */
export interface KeyExportRequestDto {
    /**
     * Passphrase that will protect the file. At least 12 characters, counted as code points, in Unicode normalization form C: the file leaves the platform and its protection is only as good as this value.
     * @type {string}
     * @memberof KeyExportRequestDto
     */
    passphrase: string;
    /**
     * Attributes required by the provider to export a key, from the export attribute schema
     * @type {Array<RequestAttribute>}
     * @memberof KeyExportRequestDto
     */
    exportAttributes?: Array<RequestAttribute>;
}
