// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.7.2-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Key Format
 * @export
 * @enum {string}
 */
export enum KeyFormat {
    Raw = "Raw",
    SubjectPublicKeyInfo = "SubjectPublicKeyInfo",
    PrivateKeyInfo = "PrivateKeyInfo",
    EncryptedPrivateKeyInfo = "EncryptedPrivateKeyInfo",
    Custom = "Custom",
}
