// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BaseAttributeContentDtoV3, ComplianceStatus, GroupDto, KeyAlgorithm, KeyFormat, KeyState, KeyType, KeyUsage } from './';

/**
 * @export
 * @interface KeyItemDto
 */
export interface KeyItemDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof KeyItemDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof KeyItemDto
     */
    name: string;
    /**
     * Description of the Key
     * @type {string}
     * @memberof KeyItemDto
     */
    description?: string;
    /**
     * Creation time of the Key. If the key is discovered from the connector, then it will be returned
     * @type {string}
     * @memberof KeyItemDto
     */
    creationTime: string;
    /**
     * UUID of the wrapper object
     * @type {string}
     * @memberof KeyItemDto
     */
    keyWrapperUuid: string;
    /**
     * UUID of the Token Profile
     * @type {string}
     * @memberof KeyItemDto
     */
    tokenProfileUuid?: string;
    /**
     * Name of the Token Profile
     * @type {string}
     * @memberof KeyItemDto
     */
    tokenProfileName?: string;
    /**
     * Token Instance UUID
     * @type {string}
     * @memberof KeyItemDto
     */
    tokenInstanceUuid?: string;
    /**
     * Token Instance Name
     * @type {string}
     * @memberof KeyItemDto
     */
    tokenInstanceName?: string;
    /**
     * Owner of the Key
     * @type {string}
     * @memberof KeyItemDto
     */
    owner?: string;
    /**
     * UUID of the owner of the Key
     * @type {string}
     * @memberof KeyItemDto
     */
    ownerUuid?: string;
    /**
     * Groups associated to the Key
     * @type {Array<GroupDto>}
     * @memberof KeyItemDto
     */
    groups?: Array<GroupDto>;
    /**
     * Number of associated objects
     * @type {number}
     * @memberof KeyItemDto
     */
    associations: number;
    /**
     * UUID of the key item in the Connector
     * @type {string}
     * @memberof KeyItemDto
     */
    keyReferenceUuid?: string;
    /**
     * Type of the Key
     * @type {KeyType}
     * @memberof KeyItemDto
     */
    type: KeyType;
    /**
     * Key Algorithm
     * @type {KeyAlgorithm}
     * @memberof KeyItemDto
     */
    keyAlgorithm: KeyAlgorithm;
    /**
     * Key Format
     * @type {KeyFormat}
     * @memberof KeyItemDto
     */
    format: KeyFormat;
    /**
     * Key Length
     * @type {number}
     * @memberof KeyItemDto
     */
    length: number;
    /**
     * Key Usages
     * @type {Array<KeyUsage>}
     * @memberof KeyItemDto
     */
    usage?: Array<KeyUsage>;
    /**
     * Boolean describing if the key is enabled or not
     * @type {boolean}
     * @memberof KeyItemDto
     */
    enabled: boolean;
    /**
     * Key State
     * @type {KeyState}
     * @memberof KeyItemDto
     */
    state: KeyState;
    /**
     * Key compliance status
     * @type {ComplianceStatus}
     * @memberof KeyItemDto
     */
    complianceStatus: ComplianceStatus;
    /**
     * Values of the attribute-sourced fields requested as columns, keyed by field source and then by field identifier. Present only when the listing request asked for attribute-sourced columns; a field the object has no value for is absent rather than empty, and a multi-valued attribute arrives in its stored item_order.
     * @type {{ [key: string]: { [key: string]: Array<BaseAttributeContentDtoV3>; }; }}
     * @memberof KeyItemDto
     */
    attributeValues?: { [key: string]: { [key: string]: Array<BaseAttributeContentDtoV3> } };
}
