// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.15.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AuditLoggingSettingsDto,
    ResourceLoggingSettingsDto,
} from './';

/**
 * @export
 * @interface LoggingSettingsDto
 */
export interface LoggingSettingsDto {
    /**
     * Settings of audit logging
     * @type {AuditLoggingSettingsDto}
     * @memberof LoggingSettingsDto
     */
    auditLogs: AuditLoggingSettingsDto;
    /**
     * Settings of event logging
     * @type {ResourceLoggingSettingsDto}
     * @memberof LoggingSettingsDto
     */
    eventLogs: ResourceLoggingSettingsDto;
}
