// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    BaseAttributeContentDtoV2,
    MetadataAttributeProperties,
} from './';

/**
 * Info attribute contains content that is for metadata. Its content can not be edited and is not send in requests to store.
 * @export
 * @interface MetadataAttributeV2
 */
export interface MetadataAttributeV2 {
    /**
     * UUID of the Attribute for unique identification
     * @type {string}
     * @memberof MetadataAttributeV2
     */
    uuid: string;
    /**
     * Name of the Attribute that is used for identification
     * @type {string}
     * @memberof MetadataAttributeV2
     */
    name: string;
    /**
     * Optional description of the Attribute, should contain helper text on what is expected
     * @type {string}
     * @memberof MetadataAttributeV2
     */
    description?: string;
    /**
     * Version of the attribute
     * @type {number}
     * @memberof MetadataAttributeV2
     */
    version: number;
    /**
     * Type of the Attribute
     * @type {AttributeType}
     * @memberof MetadataAttributeV2
     */
    type: AttributeType;
    /**
     * Content of the Attribute
     * @type {Array<BaseAttributeContentDtoV2>}
     * @memberof MetadataAttributeV2
     */
    content?: Array<BaseAttributeContentDtoV2>;
    /**
     * Type of the Content
     * @type {AttributeContentType}
     * @memberof MetadataAttributeV2
     */
    contentType: AttributeContentType;
    /**
     * Properties of the Attributes
     * @type {MetadataAttributeProperties}
     * @memberof MetadataAttributeV2
     */
    properties: MetadataAttributeProperties;
}


