// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.5.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ObjectAttributeContent
 */
export interface ObjectAttributeContent {
    /**
     * Content Reference
     * @type {string}
     * @memberof ObjectAttributeContent
     */
    reference?: string;
    /**
     * Object attribute value
     * @type {object}
     * @memberof ObjectAttributeContent
     */
    data?: object;
}
