// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ManagedSigningType,
    RequestAttribute,
    SigningScheme,
} from './';

/**
 * Request to configure managed signing with a one-time certificate issuance
 * @export
 * @interface OneTimeKeyManagedSigningRequestDto
 */
export interface OneTimeKeyManagedSigningRequestDto {
    /**
     * Signing scheme
     * @type {SigningScheme}
     * @memberof OneTimeKeyManagedSigningRequestDto
     */
    signingScheme: SigningScheme;
    /**
     * Managed signing type
     * @type {ManagedSigningType}
     * @memberof OneTimeKeyManagedSigningRequestDto
     */
    managedSigningType: ManagedSigningType;
    /**
     * UUID of the RA Profile used to issue the one-time signing certificate
     * @type {string}
     * @memberof OneTimeKeyManagedSigningRequestDto
     */
    raProfileUuid: string;
    /**
     * UUID of the CSR Template used for the certificate issuance request
     * @type {string}
     * @memberof OneTimeKeyManagedSigningRequestDto
     */
    csrTemplateUuid: string;
    /**
     * UUID of the Token Profile used to store and manage the issued certificate and key pair
     * @type {string}
     * @memberof OneTimeKeyManagedSigningRequestDto
     */
    tokenProfileUuid: string;
    /**
     * List of attributes required for signing operations (such as digest algorithm), provided by the Cryptography Provider Connector
     * @type {Array<RequestAttribute>}
     * @memberof OneTimeKeyManagedSigningRequestDto
     */
    signingOperationAttributes: Array<RequestAttribute>;
}


