// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    IlmSigningProtocolConfigurationListDto,
} from './';

/**
 * @export
 * @interface PaginationResponseDtoIlmSigningProtocolConfigurationListDto
 */
export interface PaginationResponseDtoIlmSigningProtocolConfigurationListDto {
    /**
     * Items returned
     * @type {Array<IlmSigningProtocolConfigurationListDto>}
     * @memberof PaginationResponseDtoIlmSigningProtocolConfigurationListDto
     */
    items: Array<IlmSigningProtocolConfigurationListDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof PaginationResponseDtoIlmSigningProtocolConfigurationListDto
     */
    itemsPerPage: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof PaginationResponseDtoIlmSigningProtocolConfigurationListDto
     */
    pageNumber: number;
    /**
     * Number of pages available
     * @type {number}
     * @memberof PaginationResponseDtoIlmSigningProtocolConfigurationListDto
     */
    totalPages: number;
    /**
     * Number of items available
     * @type {number}
     * @memberof PaginationResponseDtoIlmSigningProtocolConfigurationListDto
     */
    totalItems: number;
}
