// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.15.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PlatformEnum {
    Resource = 'Resource',
    ResourceAction = 'ResourceAction',
    FilterConditionOperator = 'FilterConditionOperator',
    FilterFieldType = 'FilterFieldType',
    FilterFieldSource = 'FilterFieldSource',
    SettingsSection = 'SettingsSection',
    AuthType = 'AuthType',
    HealthStatus = 'HealthStatus',
    ConnectorStatus = 'ConnectorStatus',
    FunctionGroupCode = 'FunctionGroupCode',
    CertificateType = 'CertificateType',
    CertificateState = 'CertificateState',
    CertificateValidationStatus = 'CertificateValidationStatus',
    CertificateFormat = 'CertificateFormat',
    CertificateFormatEncoding = 'CertificateFormatEncoding',
    CertificateValidationCheck = 'CertificateValidationCheck',
    CertificateRevocationReason = 'CertificateRevocationReason',
    CertificateRequestFormat = 'CertificateRequestFormat',
    DiscoveryStatus = 'DiscoveryStatus',
    CertificateProtocol = 'CertificateProtocol',
    CertificateSubjectType = 'CertificateSubjectType',
    CertificateKeyUsage = 'CertificateKeyUsage',
    CertificateRelationType = 'CertificateRelationType',
    OidCategory = 'OidCategory',
    KeyAlgorithm = 'KeyAlgorithm',
    KeyFormat = 'KeyFormat',
    KeyState = 'KeyState',
    KeyType = 'KeyType',
    KeyUsage = 'KeyUsage',
    KeyRequestType = 'KeyRequestType',
    KeyCompromiseReason = 'KeyCompromiseReason',
    TokenInstanceStatus = 'TokenInstanceStatus',
    DigestAlgorithm = 'DigestAlgorithm',
    RsaSignatureScheme = 'RsaSignatureScheme',
    RsaEncryptionScheme = 'RsaEncryptionScheme',
    ComplianceStatus = 'ComplianceStatus',
    ComplianceRuleStatus = 'ComplianceRuleStatus',
    AccountStatus = 'AccountStatus',
    ProtectionMethod = 'ProtectionMethod',
    CmpProfileVariant = 'CmpProfileVariant',
    AttributeType = 'AttributeType',
    AttributeContentType = 'AttributeContentType',
    AttributeConstraintType = 'AttributeConstraintType',
    AttributeValueTarget = 'AttributeValueTarget',
    ProgrammingLanguageEnum = 'ProgrammingLanguageEnum',
    SchedulerJobExecutionStatus = 'SchedulerJobExecutionStatus',
    RecipientType = 'RecipientType',
    TriggerType = 'TriggerType',
    ConditionType = 'ConditionType',
    ExecutionType = 'ExecutionType',
    ResourceEvent = 'ResourceEvent',
    Module = 'Module',
    ActorType = 'ActorType',
    AuthMethod = 'AuthMethod',
    Operation = 'Operation',
    OperationResult = 'OperationResult',
    ApprovalStatusEnum = 'ApprovalStatusEnum'
}

