// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.11.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Platform enum of the field values
 * @export
 * @enum {string}
 */
export enum PlatformEnum {
    Resource = 'Resource',
    FilterConditionOperator = 'FilterConditionOperator',
    FilterFieldType = 'FilterFieldType',
    FilterFieldSource = 'FilterFieldSource',
    SettingsSection = 'SettingsSection',
    NotificationType = 'NotificationType',
    AuthType = 'AuthType',
    HealthStatus = 'HealthStatus',
    ConnectorStatus = 'ConnectorStatus',
    FunctionGroupCode = 'FunctionGroupCode',
    CertificateType = 'CertificateType',
    CertificateState = 'CertificateState',
    CertificateValidationStatus = 'CertificateValidationStatus',
    CertificateFormat = 'CertificateFormat',
    CertificateFormatEncoding = 'CertificateFormatEncoding',
    CertificateValidationCheck = 'CertificateValidationCheck',
    CertificateRevocationReason = 'CertificateRevocationReason',
    CertificateRequestFormat = 'CertificateRequestFormat',
    DiscoveryStatus = 'DiscoveryStatus',
    KeyAlgorithm = 'KeyAlgorithm',
    KeyFormat = 'KeyFormat',
    KeyState = 'KeyState',
    KeyType = 'KeyType',
    KeyUsage = 'KeyUsage',
    KeyRequestType = 'KeyRequestType',
    KeyCompromiseReason = 'KeyCompromiseReason',
    TokenInstanceStatus = 'TokenInstanceStatus',
    DigestAlgorithm = 'DigestAlgorithm',
    RsaSignatureScheme = 'RsaSignatureScheme',
    RsaEncryptionScheme = 'RsaEncryptionScheme',
    ComplianceStatus = 'ComplianceStatus',
    ComplianceRuleStatus = 'ComplianceRuleStatus',
    AccountStatus = 'AccountStatus',
    AttributeType = 'AttributeType',
    AttributeContentType = 'AttributeContentType',
    AttributeConstraintType = 'AttributeConstraintType',
    AttributeValueTarget = 'AttributeValueTarget',
    ProgrammingLanguageEnum = 'ProgrammingLanguageEnum',
    SchedulerJobExecutionStatus = 'SchedulerJobExecutionStatus',
    TriggerType = 'TriggerType',
    ConditionType = 'ConditionType',
    ExecutionType = 'ExecutionType',
    ResourceEvent = 'ResourceEvent'
}

