// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.15.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RequestAttributeDto,
} from './';

/**
 * @export
 * @interface ProtocolCertificateAssociationsRequestDto
 */
export interface ProtocolCertificateAssociationsRequestDto {
    /**
     * UUID of the user to be associated with certificate by protocol
     * @type {string}
     * @memberof ProtocolCertificateAssociationsRequestDto
     */
    ownerUuid?: string;
    /**
     * UUIDs of the groups to be associated with certificate by protocol
     * @type {Array<string>}
     * @memberof ProtocolCertificateAssociationsRequestDto
     */
    groupUuids?: Array<string>;
    /**
     * Custom Attributes to be associated with certificate by protocol
     * @type {Array<RequestAttributeDto>}
     * @memberof ProtocolCertificateAssociationsRequestDto
     */
    customAttributes?: Array<RequestAttributeDto>;
    /**
     * @type {boolean}
     * @memberof ProtocolCertificateAssociationsRequestDto
     */
    empty?: boolean;
}
