// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.15.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RangeAttributeConstraintData
 */
export interface RangeAttributeConstraintData {
    /**
     * Start of the range for validation
     * @type {number}
     * @memberof RangeAttributeConstraintData
     */
    from?: number;
    /**
     * End of the range for validation
     * @type {number}
     * @memberof RangeAttributeConstraintData
     */
    to?: number;
}
