// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface RaProfileCertificateValidationSettingsUpdateDto
 */
export interface RaProfileCertificateValidationSettingsUpdateDto {
    /**
     * Indicator whether validation of certificates associated with RA profile should be enabled, if null, then values in platform settings will be used
     * @type {boolean}
     * @memberof RaProfileCertificateValidationSettingsUpdateDto
     */
    enabled?: boolean;
    /**
     * Frequency of validation of certificates in days, when not set, value in platform settings is used
     * @type {number}
     * @memberof RaProfileCertificateValidationSettingsUpdateDto
     */
    frequency?: number;
    /**
     * How many days before expiration should certificate validation status change to Expiring, when not set, value in platform settings is used
     * @type {number}
     * @memberof RaProfileCertificateValidationSettingsUpdateDto
     */
    expiringThreshold?: number;
}
