// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.6.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SearchFilterRequestDto } from "./";

/**
 * @export
 * @interface RemoveCertificateDto
 */
export interface RemoveCertificateDto {
    /**
     * List of Certificate UUIDs
     * @type {Array<string>}
     * @memberof RemoveCertificateDto
     */
    uuids?: Array<string>;
    /**
     * Certificate filter input
     * @type {Array<SearchFilterRequestDto>}
     * @memberof RemoveCertificateDto
     */
    filters?: Array<SearchFilterRequestDto>;
}
