// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeVersion,
    BaseAttributeContentDtoV2,
} from './';

/**
 * @export
 * @interface RequestAttributeV2
 */
export interface RequestAttributeV2 {
    /**
     * UUID of the Attribute
     * @type {string}
     * @memberof RequestAttributeV2
     */
    uuid: string;
    /**
     * Name of the Attribute
     * @type {string}
     * @memberof RequestAttributeV2
     */
    name: string;
    /**
     * Content Type of the Attribute
     * @type {AttributeContentType}
     * @memberof RequestAttributeV2
     */
    contentType: AttributeContentType;
    /**
     * @type {Array<BaseAttributeContentDtoV2>}
     * @memberof RequestAttributeV2
     */
    content?: Array<BaseAttributeContentDtoV2>;
    /**
     * Version of the Attribute
     * @type {AttributeVersion}
     * @memberof RequestAttributeV2
     */
    version: AttributeVersion;
}


