// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeResource,
    ResponseAttribute,
} from './';

/**
 * Content data for resource object defined by its attributes
 * @export
 * @interface ResourceSimpleContentData
 */
export interface ResourceSimpleContentData {
    /**
     * Resource contained in data
     * @type {AttributeResource}
     * @memberof ResourceSimpleContentData
     */
    resource: AttributeResource;
    /**
     * Resource identifier
     * @type {string}
     * @memberof ResourceSimpleContentData
     */
    uuid: string;
    /**
     * Resource name
     * @type {string}
     * @memberof ResourceSimpleContentData
     */
    name: string;
    /**
     * Attributes of the resource object
     * @type {Array<ResponseAttribute>}
     * @memberof ResourceSimpleContentData
     */
    attributes?: Array<ResponseAttribute>;
}


