// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.5.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Type of the resource
 * @export
 * @enum {string}
 */
export enum Resource {
    None = 'NONE',
    Dashboard = 'dashboard',
    AuditLogs = 'auditLogs',
    Credentials = 'credentials',
    Connectors = 'connectors',
    Users = 'users',
    Roles = 'roles',
    AcmeAccounts = 'acmeAccounts',
    AcmeProfiles = 'acmeProfiles',
    Authorities = 'authorities',
    RaProfiles = 'raProfiles',
    Certificates = 'certificates',
    Groups = 'groups',
    ComplianceProfiles = 'complianceProfiles',
    Discoveries = 'discoveries',
    Entities = 'entities',
    Locations = 'locations',
    TokenProfiles = 'tokenProfiles',
    Tokens = 'tokens',
    Keys = 'keys',
    Attributes = 'attributes'
}

