// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.0
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    BaseAttributeContentDto,
    NameAndUuidDto,
} from './';

/**
 * Response metadata attribute instance with content
 * @export
 * @interface ResponseMetadataDto
 */
export interface ResponseMetadataDto {
    /**
     * UUID of the Attribute
     * @type {string}
     * @memberof ResponseMetadataDto
     */
    uuid?: string;
    /**
     * Name of the Attribute
     * @type {string}
     * @memberof ResponseMetadataDto
     */
    name: string;
    /**
     * Label of the the Attribute
     * @type {string}
     * @memberof ResponseMetadataDto
     */
    label: string;
    /**
     * Type of the Attribute
     * @type {AttributeType}
     * @memberof ResponseMetadataDto
     */
    type: AttributeType;
    /**
     * Content Type of the Attribute
     * @type {AttributeContentType}
     * @memberof ResponseMetadataDto
     */
    contentType: AttributeContentType;
    /**
     * Content of the Attribute
     * @type {Array<BaseAttributeContentDto>}
     * @memberof ResponseMetadataDto
     */
    content?: Array<BaseAttributeContentDto>;
    /**
     * Source Objects
     * @type {Array<NameAndUuidDto>}
     * @memberof ResponseMetadataDto
     */
    sourceObjects: Array<NameAndUuidDto>;
}


