// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeContentDtoV2,
    ResponseAttributeV2,
    ResponseAttributeV3,
} from './';

/**
 * @type ResponseAttribute
 * Response attribute to send attribute content for object
 * @export
 */
export type ResponseAttribute = ResponseAttributeV2 | ResponseAttributeV3;
