// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 1.6.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttributeDto } from "./";

/**
 * @export
 * @interface RoleRequestDto
 */
export interface RoleRequestDto {
    /**
     * Name of the role
     * @type {string}
     * @memberof RoleRequestDto
     */
    name?: string;
    /**
     * Description for the role
     * @type {string}
     * @memberof RoleRequestDto
     */
    description?: string;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttributeDto>}
     * @memberof RoleRequestDto
     */
    customAttributes?: Array<RequestAttributeDto>;
}
