// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.11.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Resource,
    RuleConditionDto,
} from './';

/**
 * @export
 * @interface RuleConditionGroupDetailDto
 */
export interface RuleConditionGroupDetailDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof RuleConditionGroupDetailDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof RuleConditionGroupDetailDto
     */
    name: string;
    /**
     * Description of the Rule Condition Group
     * @type {string}
     * @memberof RuleConditionGroupDetailDto
     */
    description?: string;
    /**
     * @type {Resource}
     * @memberof RuleConditionGroupDetailDto
     */
    resource: Resource;
    /**
     * List of the Rule Conditions in the Rule Condition Group
     * @type {Array<RuleConditionDto>}
     * @memberof RuleConditionGroupDetailDto
     */
    conditions: Array<RuleConditionDto>;
}


