// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.11.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Resource,
    RuleActionDto,
} from './';

/**
 * List of Action Groups in the Rule Trigger
 * @export
 * @interface RuleActionGroupDto
 */
export interface RuleActionGroupDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof RuleActionGroupDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof RuleActionGroupDto
     */
    name: string;
    /**
     * Description of the Rule Action Group
     * @type {string}
     * @memberof RuleActionGroupDto
     */
    description?: string;
    /**
     * @type {Resource}
     * @memberof RuleActionGroupDto
     */
    resource: Resource;
    /**
     * List of Rule Actions in the Rule Actions Group
     * @type {Array<RuleActionDto>}
     * @memberof RuleActionGroupDto
     */
    actions: Array<RuleActionDto>;
}


