// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RequestAttribute,
    SecretContent,
} from './';

/**
 * @export
 * @interface SecretRequestDto
 */
export interface SecretRequestDto {
    /**
     * Name of the secret
     * @type {string}
     * @memberof SecretRequestDto
     */
    name: string;
    /**
     * Description of the secret
     * @type {string}
     * @memberof SecretRequestDto
     */
    description: string;
    /**
     * UUID of the vault profile where the secret is stored
     * @type {string}
     * @memberof SecretRequestDto
     */
    sourceVaultProfileUuid: string;
    /**
     * Content of the secret
     * @type {SecretContent}
     * @memberof SecretRequestDto
     */
    secret: SecretContent;
    /**
     * List of attributes associated with the secret
     * @type {Array<RequestAttribute>}
     * @memberof SecretRequestDto
     */
    attributes: Array<RequestAttribute>;
    /**
     * List of custom attributes associated with the secret
     * @type {Array<RequestAttribute>}
     * @memberof SecretRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
}
