// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ApiKeySecretContent,
    BasicAuthSecretContent,
    GenericSecretContent,
    JwtTokenSecretContent,
    KeyStoreSecretContent,
    KeyStoreType,
    KeyValueSecretContent,
    PrivateKeySecretContent,
    SecretKeySecretContent,
    SecretType,
} from './';

/**
 * @type SecretContent
 * Secret content dependent on secret type
 * @export
 */
export type SecretContent =
    | ApiKeySecretContent
    | BasicAuthSecretContent
    | GenericSecretContent
    | JwtTokenSecretContent
    | KeyStoreSecretContent
    | KeyValueSecretContent
    | PrivateKeySecretContent
    | SecretKeySecretContent;
