// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Secret attribute content data
 * @export
 * @interface SecretAttributeContentData
 */
export interface SecretAttributeContentData {
    /**
     * Secret attribute data
     * @type {string}
     * @memberof SecretAttributeContentData
     */
    secret?: string;
    /**
     * Level of protection of the data
     * @type {string}
     * @memberof SecretAttributeContentData
     */
    protectionLevel?: string;
}
