// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    RequestAttribute,
    SignatureRequestData,
} from './';

/**
 * @export
 * @interface SignDataRequestDto
 */
export interface SignDataRequestDto {
    /**
     * List of signature Attributes
     * @type {Array<RequestAttribute>}
     * @memberof SignDataRequestDto
     */
    signatureAttributes: Array<RequestAttribute>;
    /**
     * Data to be signed
     * @type {Array<SignatureRequestData>}
     * @memberof SignDataRequestDto
     */
    data: Array<SignatureRequestData>;
}
