// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    DelegatedSigningDto,
    ManagedSigningSchemeInterface,
    ManagedSigningType,
    NameAndUuidDto,
    ResponseAttribute,
    SigningScheme,
} from './';

/**
 * @type SigningSchemeInterface
 * Signing Scheme configuration dependent on signing scheme
 * @export
 */
export type SigningSchemeInterface = DelegatedSigningDto | ManagedSigningSchemeInterface;
