// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.1
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface SourceRecord
 */
export interface SourceRecord {
    /**
     * @type {string}
     * @memberof SourceRecord
     */
    method: string;
    /**
     * @type {string}
     * @memberof SourceRecord
     */
    path: string;
    /**
     * @type {string}
     * @memberof SourceRecord
     */
    contentType?: string;
    /**
     * @type {string}
     * @memberof SourceRecord
     */
    ipAddress?: string;
    /**
     * @type {string}
     * @memberof SourceRecord
     */
    userAgent?: string;
}
