// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.14.1-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface TextAttributeContent
 */
export interface TextAttributeContent {
    /**
     * Content Reference
     * @type {string}
     * @memberof TextAttributeContent
     */
    reference?: string;
    /**
     * Text attribute value
     * @type {string}
     * @memberof TextAttributeContent
     */
    data: string;
}
