// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MetadataResponseDto, ResponseAttribute, TokenInstanceStatusDetailDto } from './';

/**
 * @export
 * @interface TokenInstanceDetailDto
 */
export interface TokenInstanceDetailDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TokenInstanceDetailDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TokenInstanceDetailDto
     */
    name: string;
    /**
     * Connector Name
     * @type {string}
     * @memberof TokenInstanceDetailDto
     */
    connectorName?: string;
    /**
     * Connector UUID
     * @type {string}
     * @memberof TokenInstanceDetailDto
     */
    connectorUuid?: string;
    /**
     * Connector kind. Required for connectors based on version 1 of the connector framework; omitted for connectors based on version 2 (NG) of the connector framework.
     * @type {string}
     * @memberof TokenInstanceDetailDto
     */
    kind?: string;
    /**
     * Status Of the Token Instance
     * @type {TokenInstanceStatusDetailDto}
     * @memberof TokenInstanceDetailDto
     */
    status: TokenInstanceStatusDetailDto;
    /**
     * Number of Token Profiles associated
     * @type {number}
     * @memberof TokenInstanceDetailDto
     */
    tokenProfiles: number;
    /**
     * List of Token instance Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof TokenInstanceDetailDto
     */
    attributes: Array<ResponseAttribute>;
    /**
     * Token instance Metadata
     * @type {Array<MetadataResponseDto>}
     * @memberof TokenInstanceDetailDto
     */
    metadata?: Array<MetadataResponseDto>;
    /**
     * Custom Attributes for the Token Instance
     * @type {Array<ResponseAttribute>}
     * @memberof TokenInstanceDetailDto
     */
    customAttributes?: Array<ResponseAttribute>;
}
