// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * @export
 * @interface TokenInstanceRequestDto
 */
export interface TokenInstanceRequestDto {
    /**
     * Name of the Token Instance
     * @type {string}
     * @memberof TokenInstanceRequestDto
     */
    name: string;
    /**
     * Token Instance description
     * @type {string}
     * @memberof TokenInstanceRequestDto
     */
    description?: string;
    /**
     * UUID of the Connector
     * @type {string}
     * @memberof TokenInstanceRequestDto
     */
    connectorUuid: string;
    /**
     * Connector kind. Required for connectors based on version 1 of the connector framework; omitted for connectors based on version 2 (NG) of the connector framework.
     * @type {string}
     * @memberof TokenInstanceRequestDto
     */
    kind?: string;
    /**
     * Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof TokenInstanceRequestDto
     */
    customAttributes: Array<RequestAttribute>;
    /**
     * Attributes for Token Instance
     * @type {Array<RequestAttribute>}
     * @memberof TokenInstanceRequestDto
     */
    attributes: Array<RequestAttribute>;
}
