// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.1
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ConditionDto,
    ExecutionDto,
} from './';

/**
 * @export
 * @interface TriggerHistoryRecordDto
 */
export interface TriggerHistoryRecordDto {
    /**
     * Message with cause of action/condition failure.
     * @type {string}
     * @memberof TriggerHistoryRecordDto
     */
    message: string;
    /**
     * Condition that is referenced by history record
     * @type {ConditionDto}
     * @memberof TriggerHistoryRecordDto
     */
    condition?: ConditionDto;
    /**
     * Execution that is referenced by history record
     * @type {ExecutionDto}
     * @memberof TriggerHistoryRecordDto
     */
    execution?: ExecutionDto;
}
