// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.1
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Resource,
    TriggerHistoryObjectSummaryDto,
} from './';

/**
 * @export
 * @interface TriggerHistorySummaryDto
 */
export interface TriggerHistorySummaryDto {
    /**
     * Resource of the object associated with triggers.
     * @type {Resource}
     * @memberof TriggerHistorySummaryDto
     */
    associationResource: Resource;
    /**
     * UUID of the object associated with triggers.
     * @type {string}
     * @memberof TriggerHistorySummaryDto
     */
    associationObjectUuid: string;
    /**
     * Resource of objects that triggers has been evaluated on.
     * @type {Resource}
     * @memberof TriggerHistorySummaryDto
     */
    objectsResource: Resource;
    /**
     * Number of objects evaluated.
     * @type {number}
     * @memberof TriggerHistorySummaryDto
     */
    objectsEvaluated: number;
    /**
     * Number of objects matched at least by one trigger.
     * @type {number}
     * @memberof TriggerHistorySummaryDto
     */
    objectsMatched: number;
    /**
     * Number of objects matched by ignore triggers.
     * @type {number}
     * @memberof TriggerHistorySummaryDto
     */
    objectsIgnored: number;
    /**
     * List of history of objects that triggers has been evaluated on.
     * @type {Array<TriggerHistoryObjectSummaryDto>}
     * @memberof TriggerHistorySummaryDto
     */
    objects: Array<TriggerHistoryObjectSummaryDto>;
}


