// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ActionDetailDto,
    Resource,
    ResourceEvent,
    RuleDetailDto,
    TriggerType,
} from './';

/**
 * @export
 * @interface TriggerDetailDto
 */
export interface TriggerDetailDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TriggerDetailDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TriggerDetailDto
     */
    name: string;
    /**
     * Description of the trigger
     * @type {string}
     * @memberof TriggerDetailDto
     */
    description?: string;
    /**
     * Type of the trigger
     * @type {TriggerType}
     * @memberof TriggerDetailDto
     */
    type?: TriggerType;
    /**
     * Resource associated with the trigger
     * @type {Resource}
     * @memberof TriggerDetailDto
     */
    resource: Resource;
    /**
     * Flag if to ignore object when trigger rules are matched and do not perform any actions and stop evaluating other triggers. Based on context could have other implications to object processing. If ignore is set, trigger does not have any actions.
     * @type {boolean}
     * @memberof TriggerDetailDto
     */
    ignoreTrigger: boolean;
    /**
     * Event that trigger can be assigned to
     * @type {ResourceEvent}
     * @memberof TriggerDetailDto
     */
    event?: ResourceEvent;
    /**
     * List of Rules in the Rule Trigger
     * @type {Array<RuleDetailDto>}
     * @memberof TriggerDetailDto
     */
    rules: Array<RuleDetailDto>;
    /**
     * List of Action Groups in the Rule Trigger
     * @type {Array<ActionDetailDto>}
     * @memberof TriggerDetailDto
     */
    actions: Array<ActionDetailDto>;
}


