// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ResponseAttribute,
    SimplifiedSigningProfileDto,
} from './';

/**
 * TSP (Timestamping Protocol) configuration details
 * @export
 * @interface TspConfigurationDto
 */
export interface TspConfigurationDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TspConfigurationDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TspConfigurationDto
     */
    name: string;
    /**
     * Description of the TSP Configuration
     * @type {string}
     * @memberof TspConfigurationDto
     */
    description?: string;
    /**
     * Enabled flag of the TSP Configuration
     * @type {boolean}
     * @memberof TspConfigurationDto
     */
    enabled: boolean;
    /**
     * Default Signing Profile
     * @type {SimplifiedSigningProfileDto}
     * @memberof TspConfigurationDto
     */
    defaultSigningProfile?: SimplifiedSigningProfileDto;
    /**
     * TSP URL for signing
     * @type {string}
     * @memberof TspConfigurationDto
     */
    signingUrl?: string;
    /**
     * List of Custom Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof TspConfigurationDto
     */
    customAttributes?: Array<ResponseAttribute>;
}
