// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    ExecutionItemRequestDto,
} from './';

/**
 * @export
 * @interface UpdateExecutionRequestDto
 */
export interface UpdateExecutionRequestDto {
    /**
     * Description of the execution
     * @type {string}
     * @memberof UpdateExecutionRequestDto
     */
    description?: string;
    /**
     * List of the execution items to add to execution
     * @type {Array<ExecutionItemRequestDto>}
     * @memberof UpdateExecutionRequestDto
     */
    items: Array<ExecutionItemRequestDto>;
}
