// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.11.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Resource,
    RuleActionGroupRequestDto,
    RuleActionRequestDto,
    RuleRequestDto,
    RuleTriggerType,
} from './';

/**
 * @export
 * @interface UpdateRuleTriggerRequestDto
 */
export interface UpdateRuleTriggerRequestDto {
    /**
     * Description of the Rule Trigger
     * @type {string}
     * @memberof UpdateRuleTriggerRequestDto
     */
    description?: string;
    /**
     * @type {RuleTriggerType}
     * @memberof UpdateRuleTriggerRequestDto
     */
    triggerType: RuleTriggerType;
    /**
     * Name of the event of the Rule Trigger
     * @type {string}
     * @memberof UpdateRuleTriggerRequestDto
     */
    eventName?: string;
    /**
     * @type {Resource}
     * @memberof UpdateRuleTriggerRequestDto
     */
    triggerResource?: Resource;
    /**
     * UUID of the the Rule Trigger event source object
     * @type {string}
     * @memberof UpdateRuleTriggerRequestDto
     */
    triggerResourceUuid?: string;
    /**
     * List of new Rules to add in the Rule Trigger
     * @type {Array<RuleRequestDto>}
     * @memberof UpdateRuleTriggerRequestDto
     */
    rules?: Array<RuleRequestDto>;
    /**
     * List of UUIDs of existing Rules to add in the Rule Trigger
     * @type {Array<string>}
     * @memberof UpdateRuleTriggerRequestDto
     */
    rulesUuids?: Array<string>;
    /**
     * List of new Action Groups to add in the Rule Trigger
     * @type {Array<RuleActionGroupRequestDto>}
     * @memberof UpdateRuleTriggerRequestDto
     */
    actionGroups?: Array<RuleActionGroupRequestDto>;
    /**
     * List of UUIDs of existing Action Groups to add in the Rule Trigger
     * @type {Array<string>}
     * @memberof UpdateRuleTriggerRequestDto
     */
    actionGroupsUuids?: Array<string>;
    /**
     * List of new Rule Actions to add in the Rule Trigger
     * @type {Array<RuleActionRequestDto>}
     * @memberof UpdateRuleTriggerRequestDto
     */
    actions?: Array<RuleActionRequestDto>;
}


