// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Resource, ResourceActionsDto } from './';

/**
 * @export
 * @interface UserProfilePermissionsDto
 */
export interface UserProfilePermissionsDto {
    /**
     * Allowed resource listings
     * @type {Array<Resource>}
     * @memberof UserProfilePermissionsDto
     */
    allowedListings: Array<Resource>;
    /**
     * Actions the user is permitted to perform on a resource as a whole, per resource
     * @type {Array<ResourceActionsDto>}
     * @memberof UserProfilePermissionsDto
     */
    allowedActions: Array<ResourceActionsDto>;
}
