// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * @export
 * @interface VaultProfileUpdateRequestDto
 */
export interface VaultProfileUpdateRequestDto {
    /**
     * Description of the Vault profile
     * @type {string}
     * @memberof VaultProfileUpdateRequestDto
     */
    description?: string;
    /**
     * List of attributes of the Vault profile
     * @type {Array<RequestAttribute>}
     * @memberof VaultProfileUpdateRequestDto
     */
    attributes: Array<RequestAttribute>;
    /**
     * List of custom attributes of the Vault profile
     * @type {Array<RequestAttribute>}
     * @memberof VaultProfileUpdateRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
}
