// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    ApprovalResponseDto,
    AuthenticationServiceExceptionDto,
    BaseAttributeDto,
    BulkOperationResponse,
    CertificateChainDownloadResponseDto,
    CertificateChainResponseDto,
    CertificateComplianceCheckDto,
    CertificateContentDto,
    CertificateDetailDto,
    CertificateDownloadResponseDto,
    CertificateEventHistoryDto,
    CertificateFormat,
    CertificateFormatEncoding,
    CertificateImportRequestDto,
    CertificateImportResponseDto,
    CertificateKeystoreRequestDto,
    CertificateRelationsDto,
    CertificateResponseDto,
    CertificateSearchRequestDto,
    CertificateUpdateObjectsDto,
    CertificateValidationResultDto,
    ClientCertificateRequestDto,
    ErrorMessageDto,
    FingerprintDto,
    LocationDto,
    MultipleCertificateObjectUpdateDto,
    ProblemDetailExtended,
    RemoveCertificateDto,
    SearchFieldDataByGroupDto,
    UploadCertificateRequestDto,
    UuidDto,
} from '../models';

export interface ArchiveCertificateRequest {
    uuid: string;
}

export interface AssociateCertificatesRequest {
    uuid: string;
    certificateUuid: string;
}

export interface BulkArchiveCertificateRequest {
    requestBody: Array<string>;
}

export interface BulkDeleteCertificateRequest {
    removeCertificateDto: RemoveCertificateDto;
}

export interface BulkUnarchiveCertificateRequest {
    requestBody: Array<string>;
}

export interface BulkUpdateCertificateObjectsRequest {
    multipleCertificateObjectUpdateDto: MultipleCertificateObjectUpdateDto;
}

export interface CheckCertificatesComplianceRequest {
    certificateComplianceCheckDto: CertificateComplianceCheckDto;
}

export interface DeleteCertificateRequest {
    uuid: string;
}

export interface DownloadCertificateRequest {
    uuid: string;
    certificateFormat: CertificateFormat;
    encoding: CertificateFormatEncoding;
}

export interface DownloadCertificateChainRequest {
    uuid: string;
    certificateFormat: CertificateFormat;
    encoding: CertificateFormatEncoding;
    withEndCertificate?: boolean;
}

export interface DownloadKeystoreRequest {
    uuid: string;
    certificateKeystoreRequestDto: CertificateKeystoreRequestDto;
}

export interface GetCertificateRequest {
    uuid: string;
}

export interface GetCertificateChainRequest {
    uuid: string;
    withEndCertificate?: boolean;
}

export interface GetCertificateContentRequest {
    requestBody: Array<string>;
}

export interface GetCertificateEventHistoryRequest {
    uuid: string;
}

export interface GetCertificateRelationsRequest {
    uuid: string;
}

export interface GetCertificateValidationResultRequest {
    uuid: string;
}

export interface GetCsrGenerationAttributesRequest {
    raProfileUuid?: string;
}

export interface ImportCertificatesRequest {
    certificateImportRequestDto: CertificateImportRequestDto;
}

export interface ListCertificateApprovalsRequest {
    uuid: string;
    itemsPerPage?: number;
    pageNumber?: number;
}

export interface ListCertificateLocationsRequest {
    certificateUuid: string;
}

export interface ListCertificatesRequest {
    certificateSearchRequestDto: CertificateSearchRequestDto;
}

export interface RemoveCertificateAssociationRequest {
    uuid: string;
    certificateUuid: string;
}

export interface SubmitCertificateRequestRequest {
    clientCertificateRequestDto: ClientCertificateRequestDto;
}

export interface UnarchiveCertificateRequest {
    uuid: string;
}

export interface UpdateCertificateObjectsRequest {
    uuid: string;
    certificateUpdateObjectsDto: CertificateUpdateObjectsDto;
}

export interface UploadRequest {
    uploadCertificateRequestDto: UploadCertificateRequestDto;
}

export interface UploadAsyncRequest {
    uploadCertificateRequestDto: UploadCertificateRequestDto;
}

/**
 * no description
 */
export class CertificateInventoryApi extends BaseAPI {
    /**
     * Archive a certificate
     */
    archiveCertificate({ uuid }: ArchiveCertificateRequest): Observable<void>;
    archiveCertificate({ uuid }: ArchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    archiveCertificate({ uuid }: ArchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'archiveCertificate');

        return this.request<void>(
            {
                url: '/v1/certificates/{uuid}/archive'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Associate a source certificate to the given certificate
     */
    associateCertificates({ uuid, certificateUuid }: AssociateCertificatesRequest): Observable<void>;
    associateCertificates(
        { uuid, certificateUuid }: AssociateCertificatesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    associateCertificates(
        { uuid, certificateUuid }: AssociateCertificatesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'associateCertificates');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'associateCertificates');

        return this.request<void>(
            {
                url: '/v1/certificates/{uuid}/relations/{certificateUuid}'
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Archive a list of certificates
     */
    bulkArchiveCertificate({ requestBody }: BulkArchiveCertificateRequest): Observable<void>;
    bulkArchiveCertificate({ requestBody }: BulkArchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    bulkArchiveCertificate({ requestBody }: BulkArchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkArchiveCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v1/certificates/archive',
                method: 'PATCH',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * In this operation, when the list of Certificate UUIDs are provided and the filter is left as null or undefined, then the change will be applied only to the list of Certificate UUIDs provided. When the filter is provided in the request, the list of UUIDs will be ignored and the change will be applied for the all the certificates that matches the filter criteria. To apply this change for all the Certificates in the inventory, provide an empty array \"[]\" for the value of \"filters\" in the request body
     * Delete multiple certificates
     */
    bulkDeleteCertificate({ removeCertificateDto }: BulkDeleteCertificateRequest): Observable<BulkOperationResponse>;
    bulkDeleteCertificate(
        { removeCertificateDto }: BulkDeleteCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<BulkOperationResponse>>;
    bulkDeleteCertificate(
        { removeCertificateDto }: BulkDeleteCertificateRequest,
        opts?: OperationOpts,
    ): Observable<BulkOperationResponse | AjaxResponse<BulkOperationResponse>> {
        throwIfNullOrUndefined(removeCertificateDto, 'removeCertificateDto', 'bulkDeleteCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<BulkOperationResponse>(
            {
                url: '/v1/certificates/delete',
                method: 'POST',
                headers,
                body: removeCertificateDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Unarchive a list of certificates
     */
    bulkUnarchiveCertificate({ requestBody }: BulkUnarchiveCertificateRequest): Observable<void>;
    bulkUnarchiveCertificate({ requestBody }: BulkUnarchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    bulkUnarchiveCertificate(
        { requestBody }: BulkUnarchiveCertificateRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkUnarchiveCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v1/certificates/unarchive',
                method: 'PATCH',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * In this operation, when the list of Certificate UUIDs are provided and the filter is left as null or undefined, then the change will be applied only to the list of Certificate UUIDs provided. When the filter is provided in the request, the list of UUIDs will be ignored and the change will be applied for the all the certificates that matches the filter criteria. To apply this change for all the Certificates in the inventory, provide an empty array \"[]\" for the value of \"filters\" in the request body
     * Update Group and/or Owner for multiple Certificates
     */
    bulkUpdateCertificateObjects({ multipleCertificateObjectUpdateDto }: BulkUpdateCertificateObjectsRequest): Observable<void>;
    bulkUpdateCertificateObjects(
        { multipleCertificateObjectUpdateDto }: BulkUpdateCertificateObjectsRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    bulkUpdateCertificateObjects(
        { multipleCertificateObjectUpdateDto }: BulkUpdateCertificateObjectsRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(multipleCertificateObjectUpdateDto, 'multipleCertificateObjectUpdateDto', 'bulkUpdateCertificateObjects');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v1/certificates',
                method: 'PATCH',
                headers,
                body: multipleCertificateObjectUpdateDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Initiate Certificate Compliance Check
     */
    checkCertificatesCompliance({ certificateComplianceCheckDto }: CheckCertificatesComplianceRequest): Observable<void>;
    checkCertificatesCompliance(
        { certificateComplianceCheckDto }: CheckCertificatesComplianceRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    checkCertificatesCompliance(
        { certificateComplianceCheckDto }: CheckCertificatesComplianceRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(certificateComplianceCheckDto, 'certificateComplianceCheckDto', 'checkCertificatesCompliance');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v1/certificates/compliance',
                method: 'POST',
                headers,
                body: certificateComplianceCheckDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete a certificate
     */
    deleteCertificate({ uuid }: DeleteCertificateRequest): Observable<void>;
    deleteCertificate({ uuid }: DeleteCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    deleteCertificate({ uuid }: DeleteCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteCertificate');

        return this.request<void>(
            {
                url: '/v1/certificates/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Download Certificate
     */
    downloadCertificate({ uuid, certificateFormat, encoding }: DownloadCertificateRequest): Observable<CertificateDownloadResponseDto>;
    downloadCertificate(
        { uuid, certificateFormat, encoding }: DownloadCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateDownloadResponseDto>>;
    downloadCertificate(
        { uuid, certificateFormat, encoding }: DownloadCertificateRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDownloadResponseDto | AjaxResponse<CertificateDownloadResponseDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'downloadCertificate');
        throwIfNullOrUndefined(certificateFormat, 'certificateFormat', 'downloadCertificate');
        throwIfNullOrUndefined(encoding, 'encoding', 'downloadCertificate');

        const queryParams: HttpQuery = {
            // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            encoding: encoding,
        };

        return this.request<CertificateDownloadResponseDto>(
            {
                url: '/v1/certificates/{uuid}/{certificateFormat}'
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{certificateFormat}', encodeURI(certificateFormat)),
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Download Certificate Chain in chosen format
     */
    downloadCertificateChain({
        uuid,
        certificateFormat,
        encoding,
        withEndCertificate,
    }: DownloadCertificateChainRequest): Observable<CertificateChainDownloadResponseDto>;
    downloadCertificateChain(
        { uuid, certificateFormat, encoding, withEndCertificate }: DownloadCertificateChainRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateChainDownloadResponseDto>>;
    downloadCertificateChain(
        { uuid, certificateFormat, encoding, withEndCertificate }: DownloadCertificateChainRequest,
        opts?: OperationOpts,
    ): Observable<CertificateChainDownloadResponseDto | AjaxResponse<CertificateChainDownloadResponseDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'downloadCertificateChain');
        throwIfNullOrUndefined(certificateFormat, 'certificateFormat', 'downloadCertificateChain');
        throwIfNullOrUndefined(encoding, 'encoding', 'downloadCertificateChain');

        const queryParams: HttpQuery = {
            // required parameters are used directly since they are already checked by throwIfNullOrUndefined
            encoding: encoding,
        };

        if (withEndCertificate != null) {
            queryParams['withEndCertificate'] = withEndCertificate;
        }

        return this.request<CertificateChainDownloadResponseDto>(
            {
                url: '/v1/certificates/{uuid}/chain/{certificateFormat}'
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{certificateFormat}', encodeURI(certificateFormat)),
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Download a certificate, its chain and its private key as one PKCS#12 file.  This is a POST because the passphrase travels in the body: a URL is recorded by proxies, browser history and access logs, so a passphrase must never appear in one. The response is not cacheable and carries a sanitized download filename.  It is a separate operation from the certificate content download, which serves certificates only. Only a key created or imported as exportable can be included.
     * Download a certificate with its private key
     */
    downloadKeystore({ uuid, certificateKeystoreRequestDto }: DownloadKeystoreRequest): Observable<Blob>;
    downloadKeystore(
        { uuid, certificateKeystoreRequestDto }: DownloadKeystoreRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Blob>>;
    downloadKeystore(
        { uuid, certificateKeystoreRequestDto }: DownloadKeystoreRequest,
        opts?: OperationOpts,
    ): Observable<Blob | AjaxResponse<Blob>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'downloadKeystore');
        throwIfNullOrUndefined(certificateKeystoreRequestDto, 'certificateKeystoreRequestDto', 'downloadKeystore');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Blob>(
            {
                url: '/v1/certificates/{uuid}/keystore'.replace('{uuid}', encodeURI(uuid)),
                method: 'POST',
                headers,
                body: certificateKeystoreRequestDto,
                responseType: 'blob',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Certificate Details
     */
    getCertificate({ uuid }: GetCertificateRequest): Observable<CertificateDetailDto>;
    getCertificate({ uuid }: GetCertificateRequest, opts?: OperationOpts): Observable<AjaxResponse<CertificateDetailDto>>;
    getCertificate(
        { uuid }: GetCertificateRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDetailDto | AjaxResponse<CertificateDetailDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCertificate');

        return this.request<CertificateDetailDto>(
            {
                url: '/v1/certificates/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get certificate chain for the certificate with the given UUID. The certificate chain is returned in the order of the chain, with the first certificate being the certificate with the given UUID, up to the last identified certificate in the chain. If the certificate with the given UUID has status `NEW` or `REJECTED`, an empty list is returned.
     * Get certificate chain
     */
    getCertificateChain({ uuid, withEndCertificate }: GetCertificateChainRequest): Observable<CertificateChainResponseDto>;
    getCertificateChain(
        { uuid, withEndCertificate }: GetCertificateChainRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateChainResponseDto>>;
    getCertificateChain(
        { uuid, withEndCertificate }: GetCertificateChainRequest,
        opts?: OperationOpts,
    ): Observable<CertificateChainResponseDto | AjaxResponse<CertificateChainResponseDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCertificateChain');

        const queryParams: HttpQuery = {};

        if (withEndCertificate != null) {
            queryParams['withEndCertificate'] = withEndCertificate;
        }

        return this.request<CertificateChainResponseDto>(
            {
                url: '/v1/certificates/{uuid}/chain'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Certificate Content
     */
    getCertificateContent({ requestBody }: GetCertificateContentRequest): Observable<Array<CertificateContentDto>>;
    getCertificateContent(
        { requestBody }: GetCertificateContentRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<CertificateContentDto>>>;
    getCertificateContent(
        { requestBody }: GetCertificateContentRequest,
        opts?: OperationOpts,
    ): Observable<Array<CertificateContentDto> | AjaxResponse<Array<CertificateContentDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'getCertificateContent');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<CertificateContentDto>>(
            {
                url: '/v1/certificates/content',
                method: 'POST',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Certificate event history
     */
    getCertificateEventHistory({ uuid }: GetCertificateEventHistoryRequest): Observable<Array<CertificateEventHistoryDto>>;
    getCertificateEventHistory(
        { uuid }: GetCertificateEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<CertificateEventHistoryDto>>>;
    getCertificateEventHistory(
        { uuid }: GetCertificateEventHistoryRequest,
        opts?: OperationOpts,
    ): Observable<Array<CertificateEventHistoryDto> | AjaxResponse<Array<CertificateEventHistoryDto>>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCertificateEventHistory');

        return this.request<Array<CertificateEventHistoryDto>>(
            {
                url: '/v1/certificates/{uuid}/history'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get relations for a certificate
     */
    getCertificateRelations({ uuid }: GetCertificateRelationsRequest): Observable<CertificateRelationsDto>;
    getCertificateRelations(
        { uuid }: GetCertificateRelationsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateRelationsDto>>;
    getCertificateRelations(
        { uuid }: GetCertificateRelationsRequest,
        opts?: OperationOpts,
    ): Observable<CertificateRelationsDto | AjaxResponse<CertificateRelationsDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCertificateRelations');

        return this.request<CertificateRelationsDto>(
            {
                url: '/v1/certificates/{uuid}/relations'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Besides the conditions a field may be filtered with, each field reports whether it can serve as a configurable column of the listing: `displayable` marks the fields that may be named in `columns`, and `sortable` those the listing may be ordered by. A field that reports neither flag is filter-only, so an absent flag is to be read as `false` rather than as unknown.  Both flags are answered per field, and that answer is authoritative for attribute-sourced fields as much as for property ones: whether a given attribute may be ordered on depends on the resource and is reported here rather than assumed. A field that may be shown but not ordered on reports `displayable` without `sortable`.
     * Get Certificate searchable fields information
     */
    getCertificateSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    getCertificateSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    getCertificateSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/certificates/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Certificate Validation Result
     */
    getCertificateValidationResult({ uuid }: GetCertificateValidationResultRequest): Observable<CertificateValidationResultDto>;
    getCertificateValidationResult(
        { uuid }: GetCertificateValidationResultRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateValidationResultDto>>;
    getCertificateValidationResult(
        { uuid }: GetCertificateValidationResultRequest,
        opts?: OperationOpts,
    ): Observable<CertificateValidationResultDto | AjaxResponse<CertificateValidationResultDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCertificateValidationResult');

        return this.request<CertificateValidationResultDto>(
            {
                url: '/v1/certificates/{uuid}/validate'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns the request-attribute definitions available for building a certificate request. Without `raProfileUuid`: the editable platform default request-attribute set. With `raProfileUuid`: the resolved request-attribute set for that RA profile.
     * Get CSR Generation Attributes
     */
    getCsrGenerationAttributes({ raProfileUuid }: GetCsrGenerationAttributesRequest): Observable<Array<BaseAttributeDto>>;
    getCsrGenerationAttributes(
        { raProfileUuid }: GetCsrGenerationAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    getCsrGenerationAttributes(
        { raProfileUuid }: GetCsrGenerationAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        const queryParams: HttpQuery = {};

        if (raProfileUuid != null) {
            queryParams['raProfileUuid'] = raProfileUuid;
        }

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/certificates/csr/attributes',
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Import named entries from an uploaded file.  The file travels base64-encoded in `file`, like every upload in the platform, and is held in memory rather than written anywhere; it is never echoed in an error, since it may carry key material. Every entry to import is named, and nothing else in the file is touched: an import never takes in material the caller did not ask for.  An entry reference is derived from the entry\'s own content — a certificate fingerprint, a public key fingerprint, or a digest of the protected key — so naming one selects that content, not a position in a file. A caller showing a user what is inside reads the file first with `POST /v1/inspections` and names what the user chose. A caller that already knows what it is importing computes the reference itself and imports in one call.  Each entry says where its own key material goes, because a file can hold entries of different key types and each key type has its own provider attribute schema.  Entries succeed or fail on their own and the response reports the outcome of each. Each entry carries its own `importId`, so repeating a request returns what already succeeded and retries only what did not: a caller recovering from a lost or partial response resends the same body and needs to work out nothing.
     * Import certificates and keys from an uploaded file
     */
    importCertificates({ certificateImportRequestDto }: ImportCertificatesRequest): Observable<CertificateImportResponseDto>;
    importCertificates(
        { certificateImportRequestDto }: ImportCertificatesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateImportResponseDto>>;
    importCertificates(
        { certificateImportRequestDto }: ImportCertificatesRequest,
        opts?: OperationOpts,
    ): Observable<CertificateImportResponseDto | AjaxResponse<CertificateImportResponseDto>> {
        throwIfNullOrUndefined(certificateImportRequestDto, 'certificateImportRequestDto', 'importCertificates');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateImportResponseDto>(
            {
                url: '/v1/certificates/import',
                method: 'POST',
                headers,
                body: certificateImportRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * List Certificates Approvals
     */
    listCertificateApprovals({ uuid, itemsPerPage, pageNumber }: ListCertificateApprovalsRequest): Observable<ApprovalResponseDto>;
    listCertificateApprovals(
        { uuid, itemsPerPage, pageNumber }: ListCertificateApprovalsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ApprovalResponseDto>>;
    listCertificateApprovals(
        { uuid, itemsPerPage, pageNumber }: ListCertificateApprovalsRequest,
        opts?: OperationOpts,
    ): Observable<ApprovalResponseDto | AjaxResponse<ApprovalResponseDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'listCertificateApprovals');

        const queryParams: HttpQuery = {};

        if (itemsPerPage != null) {
            queryParams['itemsPerPage'] = itemsPerPage;
        }
        if (pageNumber != null) {
            queryParams['pageNumber'] = pageNumber;
        }

        return this.request<ApprovalResponseDto>(
            {
                url: '/v1/certificates/{uuid}/approvals'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * List of available Locations for the Certificate
     */
    listCertificateLocations({ certificateUuid }: ListCertificateLocationsRequest): Observable<Array<LocationDto>>;
    listCertificateLocations(
        { certificateUuid }: ListCertificateLocationsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<LocationDto>>>;
    listCertificateLocations(
        { certificateUuid }: ListCertificateLocationsRequest,
        opts?: OperationOpts,
    ): Observable<Array<LocationDto> | AjaxResponse<Array<LocationDto>>> {
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'listCertificateLocations');

        return this.request<Array<LocationDto>>(
            {
                url: '/v1/certificates/{certificateUuid}/locations'.replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Ordering and columns address a field by its source together with its identifier, because an identifier is unique only within its source. Both halves, and which fields may be shown or ordered on, come from the searchable-fields operation of this resource.  `sort` orders the whole result set before it is paged, so paging walks the sorted set rather than sorting one page at a time; only fields the catalogue marks `sortable` may be used. `columns` names the fields the caller means to display, and only fields the catalogue marks `displayable` may be named. It does not narrow the response: every listing object comes back whole, and naming a property field asks for nothing extra because the object already carries it. Naming an attribute-sourced field is what has an effect, described below.  A request that carries neither `sort` nor `columns` is answered exactly as it was before the two fields existed: the endpoint\'s own default ordering, the full default shape of every object, and no `attributeValues` member. A caller written against the previous contract therefore needs no change.  Requesting attribute-sourced columns adds an `attributeValues` member to each returned object, keyed by field source and then by field identifier. A field the object holds no value for is absent rather than empty, and a multi-valued attribute arrives in its stored `item_order`.
     * List Certificates
     */
    listCertificates({ certificateSearchRequestDto }: ListCertificatesRequest): Observable<CertificateResponseDto>;
    listCertificates(
        { certificateSearchRequestDto }: ListCertificatesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateResponseDto>>;
    listCertificates(
        { certificateSearchRequestDto }: ListCertificatesRequest,
        opts?: OperationOpts,
    ): Observable<CertificateResponseDto | AjaxResponse<CertificateResponseDto>> {
        throwIfNullOrUndefined(certificateSearchRequestDto, 'certificateSearchRequestDto', 'listCertificates');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateResponseDto>(
            {
                url: '/v1/certificates',
                method: 'POST',
                headers,
                body: certificateSearchRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Remove a source certificate association from the given certificate
     */
    removeCertificateAssociation({ uuid, certificateUuid }: RemoveCertificateAssociationRequest): Observable<void>;
    removeCertificateAssociation(
        { uuid, certificateUuid }: RemoveCertificateAssociationRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    removeCertificateAssociation(
        { uuid, certificateUuid }: RemoveCertificateAssociationRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'removeCertificateAssociation');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'removeCertificateAssociation');

        return this.request<void>(
            {
                url: '/v1/certificates/{uuid}/relations/{certificateUuid}'
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Submit certificate request
     */
    submitCertificateRequest({ clientCertificateRequestDto }: SubmitCertificateRequestRequest): Observable<CertificateDetailDto>;
    submitCertificateRequest(
        { clientCertificateRequestDto }: SubmitCertificateRequestRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateDetailDto>>;
    submitCertificateRequest(
        { clientCertificateRequestDto }: SubmitCertificateRequestRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDetailDto | AjaxResponse<CertificateDetailDto>> {
        throwIfNullOrUndefined(clientCertificateRequestDto, 'clientCertificateRequestDto', 'submitCertificateRequest');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateDetailDto>(
            {
                url: '/v1/certificates/create',
                method: 'POST',
                headers,
                body: clientCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Unarchive a certificate
     */
    unarchiveCertificate({ uuid }: UnarchiveCertificateRequest): Observable<void>;
    unarchiveCertificate({ uuid }: UnarchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    unarchiveCertificate({ uuid }: UnarchiveCertificateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'unarchiveCertificate');

        return this.request<void>(
            {
                url: '/v1/certificates/{uuid}/unarchive'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Update Certificate Objects
     */
    updateCertificateObjects({ uuid, certificateUpdateObjectsDto }: UpdateCertificateObjectsRequest): Observable<void>;
    updateCertificateObjects(
        { uuid, certificateUpdateObjectsDto }: UpdateCertificateObjectsRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    updateCertificateObjects(
        { uuid, certificateUpdateObjectsDto }: UpdateCertificateObjectsRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'updateCertificateObjects');
        throwIfNullOrUndefined(certificateUpdateObjectsDto, 'certificateUpdateObjectsDto', 'updateCertificateObjects');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v1/certificates/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
                headers,
                body: certificateUpdateObjectsDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Upload a new Certificate
     */
    upload({ uploadCertificateRequestDto }: UploadRequest): Observable<UuidDto>;
    upload({ uploadCertificateRequestDto }: UploadRequest, opts?: OperationOpts): Observable<AjaxResponse<UuidDto>>;
    upload({ uploadCertificateRequestDto }: UploadRequest, opts?: OperationOpts): Observable<UuidDto | AjaxResponse<UuidDto>> {
        throwIfNullOrUndefined(uploadCertificateRequestDto, 'uploadCertificateRequestDto', 'upload');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<UuidDto>(
            {
                url: '/v1/certificates/upload',
                method: 'POST',
                headers,
                body: uploadCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Upload a new Certificate
     */
    uploadAsync({ uploadCertificateRequestDto }: UploadAsyncRequest): Observable<FingerprintDto>;
    uploadAsync({ uploadCertificateRequestDto }: UploadAsyncRequest, opts?: OperationOpts): Observable<AjaxResponse<FingerprintDto>>;
    uploadAsync(
        { uploadCertificateRequestDto }: UploadAsyncRequest,
        opts?: OperationOpts,
    ): Observable<FingerprintDto | AjaxResponse<FingerprintDto>> {
        throwIfNullOrUndefined(uploadCertificateRequestDto, 'uploadCertificateRequestDto', 'uploadAsync');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<FingerprintDto>(
            {
                url: '/v1/certificates/upload/async',
                method: 'POST',
                headers,
                body: uploadCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
