// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.12.1-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import type {
    PaginationRequestDto,
    ScheduledJobDetailDto,
    ScheduledJobHistoryResponseDto,
    ScheduledJobsResponseDto,
} from '../models';
import type { HttpQuery, OperationOpts } from '../runtime';
import { BaseAPI, encodeURI, throwIfNullOrUndefined } from '../runtime';

export interface DeleteScheduledJobRequest {
    uuid: string;
}

export interface DisableScheduledJobRequest {
    uuid: string;
}

export interface EnableScheduledJobRequest {
    uuid: string;
}

export interface GetScheduledJobDetailRequest {
    uuid: string;
}

export interface GetScheduledJobHistoryRequest {
    pagination: PaginationRequestDto;
    uuid: string;
}

export interface ListScheduledJobsRequest {
    pagination: PaginationRequestDto;
}

/**
 * no description
 */
export class ScheduledJobsManagementApi extends BaseAPI {

    /**
     * Delete Scheduled job
     */
    deleteScheduledJob({ uuid }: DeleteScheduledJobRequest): Observable<void>
    deleteScheduledJob({ uuid }: DeleteScheduledJobRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    deleteScheduledJob({ uuid }: DeleteScheduledJobRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteScheduledJob');

        return this.request<void>({
            url: '/v1/scheduler/jobs/{uuid}'.replace('{uuid}', encodeURI(uuid)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     * Disabling of Scheduled job
     */
    disableScheduledJob({ uuid }: DisableScheduledJobRequest): Observable<void>
    disableScheduledJob({ uuid }: DisableScheduledJobRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    disableScheduledJob({ uuid }: DisableScheduledJobRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'disableScheduledJob');

        return this.request<void>({
            url: '/v1/scheduler/jobs/{uuid}/disable'.replace('{uuid}', encodeURI(uuid)),
            method: 'PATCH',
        }, opts?.responseOpts);
    };

    /**
     * Enabling of Scheduled job
     */
    enableScheduledJob({ uuid }: EnableScheduledJobRequest): Observable<void>
    enableScheduledJob({ uuid }: EnableScheduledJobRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    enableScheduledJob({ uuid }: EnableScheduledJobRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'enableScheduledJob');

        return this.request<void>({
            url: '/v1/scheduler/jobs/{uuid}/enable'.replace('{uuid}', encodeURI(uuid)),
            method: 'PATCH',
        }, opts?.responseOpts);
    };

    /**
     * Scheduled job detail
     */
    getScheduledJobDetail({ uuid }: GetScheduledJobDetailRequest): Observable<ScheduledJobDetailDto>
    getScheduledJobDetail({ uuid }: GetScheduledJobDetailRequest, opts?: OperationOpts): Observable<AjaxResponse<ScheduledJobDetailDto>>
    getScheduledJobDetail({ uuid }: GetScheduledJobDetailRequest, opts?: OperationOpts): Observable<ScheduledJobDetailDto | AjaxResponse<ScheduledJobDetailDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getScheduledJobDetail');

        return this.request<ScheduledJobDetailDto>({
            url: '/v1/scheduler/jobs/{uuid}'.replace('{uuid}', encodeURI(uuid)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Scheduled job history
     */
    getScheduledJobHistory({ pagination, uuid }: GetScheduledJobHistoryRequest): Observable<ScheduledJobHistoryResponseDto>
    getScheduledJobHistory({ pagination, uuid }: GetScheduledJobHistoryRequest, opts?: OperationOpts): Observable<AjaxResponse<ScheduledJobHistoryResponseDto>>
    getScheduledJobHistory({ pagination, uuid }: GetScheduledJobHistoryRequest, opts?: OperationOpts): Observable<ScheduledJobHistoryResponseDto | AjaxResponse<ScheduledJobHistoryResponseDto>> {
        throwIfNullOrUndefined(pagination, 'pagination', 'getScheduledJobHistory');
        throwIfNullOrUndefined(uuid, 'uuid', 'getScheduledJobHistory');

        const query: HttpQuery = {};

        if (pagination != null) {
            Object.assign(query, pagination);
        }

        return this.request<ScheduledJobHistoryResponseDto>({
            url: '/v1/scheduler/jobs/{uuid}/history'.replace('{uuid}', encodeURI(uuid)),
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

    /**
     * List of scheduled jobs
     */
    listScheduledJobs({ pagination }: ListScheduledJobsRequest): Observable<ScheduledJobsResponseDto>
    listScheduledJobs({ pagination }: ListScheduledJobsRequest, opts?: OperationOpts): Observable<AjaxResponse<ScheduledJobsResponseDto>>
    listScheduledJobs({ pagination }: ListScheduledJobsRequest, opts?: OperationOpts): Observable<ScheduledJobsResponseDto | AjaxResponse<ScheduledJobsResponseDto>> {
        throwIfNullOrUndefined(pagination, 'pagination', 'listScheduledJobs');

        const query: HttpQuery = {};

        if (pagination != null) {
            Object.assign(query, pagination);
        }

        return this.request<ScheduledJobsResponseDto>({
            url: '/v1/scheduler/jobs',
            method: 'GET',
            query,
        }, opts?.responseOpts);
    };

}
