// tslint:disable
/**
 * CZERTAINLY Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.14.2-SNAPSHOT
 * Contact: info@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    AuthenticationSettingsDto,
    AuthenticationSettingsUpdateDto,
    ErrorMessageDto,
    LoggingSettingsDto,
    NotificationSettingsDto,
    OAuth2ProviderSettingsResponseDto,
    OAuth2ProviderSettingsUpdateDto,
    PlatformSettingsDto,
    PlatformSettingsUpdateDto,
} from '../models';

export interface GetOAuth2ProviderSettingsRequest {
    providerName: string;
}

export interface RemoveOAuth2ProviderRequest {
    providerName: string;
}

export interface UpdateAuthenticationSettingsRequest {
    authenticationSettingsUpdateDto: AuthenticationSettingsUpdateDto;
}

export interface UpdateLoggingSettingsRequest {
    loggingSettingsDto: LoggingSettingsDto;
}

export interface UpdateNotificationsSettingsRequest {
    notificationSettingsDto: NotificationSettingsDto;
}

export interface UpdateOAuth2ProviderSettingsRequest {
    providerName: string;
    oAuth2ProviderSettingsUpdateDto: OAuth2ProviderSettingsUpdateDto;
}

export interface UpdatePlatformSettingsRequest {
    platformSettingsUpdateDto: PlatformSettingsUpdateDto;
}

/**
 * no description
 */
export class SettingsApi extends BaseAPI {

    /**
     * Get authentication settings
     */
    getAuthenticationSettings(): Observable<AuthenticationSettingsDto>
    getAuthenticationSettings(opts?: OperationOpts): Observable<AjaxResponse<AuthenticationSettingsDto>>
    getAuthenticationSettings(opts?: OperationOpts): Observable<AuthenticationSettingsDto | AjaxResponse<AuthenticationSettingsDto>> {
        return this.request<AuthenticationSettingsDto>({
            url: '/v1/settings/authentication',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get logging settings
     */
    getLoggingSettings(): Observable<LoggingSettingsDto>
    getLoggingSettings(opts?: OperationOpts): Observable<AjaxResponse<LoggingSettingsDto>>
    getLoggingSettings(opts?: OperationOpts): Observable<LoggingSettingsDto | AjaxResponse<LoggingSettingsDto>> {
        return this.request<LoggingSettingsDto>({
            url: '/v1/settings/logging',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get notification settings
     */
    getNotificationsSettings(): Observable<NotificationSettingsDto>
    getNotificationsSettings(opts?: OperationOpts): Observable<AjaxResponse<NotificationSettingsDto>>
    getNotificationsSettings(opts?: OperationOpts): Observable<NotificationSettingsDto | AjaxResponse<NotificationSettingsDto>> {
        return this.request<NotificationSettingsDto>({
            url: '/v1/settings/notifications',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get OAuth2 Provider settings
     */
    getOAuth2ProviderSettings({ providerName }: GetOAuth2ProviderSettingsRequest): Observable<OAuth2ProviderSettingsResponseDto>
    getOAuth2ProviderSettings({ providerName }: GetOAuth2ProviderSettingsRequest, opts?: OperationOpts): Observable<AjaxResponse<OAuth2ProviderSettingsResponseDto>>
    getOAuth2ProviderSettings({ providerName }: GetOAuth2ProviderSettingsRequest, opts?: OperationOpts): Observable<OAuth2ProviderSettingsResponseDto | AjaxResponse<OAuth2ProviderSettingsResponseDto>> {
        throwIfNullOrUndefined(providerName, 'providerName', 'getOAuth2ProviderSettings');

        return this.request<OAuth2ProviderSettingsResponseDto>({
            url: '/v1/settings/authentication/oauth2Providers/{providerName}'.replace('{providerName}', encodeURI(providerName)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Get platform settings
     */
    getPlatformSettings(): Observable<PlatformSettingsDto>
    getPlatformSettings(opts?: OperationOpts): Observable<AjaxResponse<PlatformSettingsDto>>
    getPlatformSettings(opts?: OperationOpts): Observable<PlatformSettingsDto | AjaxResponse<PlatformSettingsDto>> {
        return this.request<PlatformSettingsDto>({
            url: '/v1/settings/platform',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * Remove OAuth2 Provider
     */
    removeOAuth2Provider({ providerName }: RemoveOAuth2ProviderRequest): Observable<void>
    removeOAuth2Provider({ providerName }: RemoveOAuth2ProviderRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    removeOAuth2Provider({ providerName }: RemoveOAuth2ProviderRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(providerName, 'providerName', 'removeOAuth2Provider');

        return this.request<void>({
            url: '/v1/settings/authentication/oauth2Providers/{providerName}'.replace('{providerName}', encodeURI(providerName)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     * Update authentication settings
     */
    updateAuthenticationSettings({ authenticationSettingsUpdateDto }: UpdateAuthenticationSettingsRequest): Observable<void>
    updateAuthenticationSettings({ authenticationSettingsUpdateDto }: UpdateAuthenticationSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    updateAuthenticationSettings({ authenticationSettingsUpdateDto }: UpdateAuthenticationSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authenticationSettingsUpdateDto, 'authenticationSettingsUpdateDto', 'updateAuthenticationSettings');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/v1/settings/authentication',
            method: 'PUT',
            headers,
            body: authenticationSettingsUpdateDto,
        }, opts?.responseOpts);
    };

    /**
     * Update logging setting
     */
    updateLoggingSettings({ loggingSettingsDto }: UpdateLoggingSettingsRequest): Observable<void>
    updateLoggingSettings({ loggingSettingsDto }: UpdateLoggingSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    updateLoggingSettings({ loggingSettingsDto }: UpdateLoggingSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(loggingSettingsDto, 'loggingSettingsDto', 'updateLoggingSettings');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/v1/settings/logging',
            method: 'PUT',
            headers,
            body: loggingSettingsDto,
        }, opts?.responseOpts);
    };

    /**
     * Update notifications setting
     */
    updateNotificationsSettings({ notificationSettingsDto }: UpdateNotificationsSettingsRequest): Observable<void>
    updateNotificationsSettings({ notificationSettingsDto }: UpdateNotificationsSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    updateNotificationsSettings({ notificationSettingsDto }: UpdateNotificationsSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(notificationSettingsDto, 'notificationSettingsDto', 'updateNotificationsSettings');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/v1/settings/notifications',
            method: 'PUT',
            headers,
            body: notificationSettingsDto,
        }, opts?.responseOpts);
    };

    /**
     * Update OAuth2 Provider settings
     */
    updateOAuth2ProviderSettings({ providerName, oAuth2ProviderSettingsUpdateDto }: UpdateOAuth2ProviderSettingsRequest): Observable<void>
    updateOAuth2ProviderSettings({ providerName, oAuth2ProviderSettingsUpdateDto }: UpdateOAuth2ProviderSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    updateOAuth2ProviderSettings({ providerName, oAuth2ProviderSettingsUpdateDto }: UpdateOAuth2ProviderSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(providerName, 'providerName', 'updateOAuth2ProviderSettings');
        throwIfNullOrUndefined(oAuth2ProviderSettingsUpdateDto, 'oAuth2ProviderSettingsUpdateDto', 'updateOAuth2ProviderSettings');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/v1/settings/authentication/oauth2Providers/{providerName}'.replace('{providerName}', encodeURI(providerName)),
            method: 'PUT',
            headers,
            body: oAuth2ProviderSettingsUpdateDto,
        }, opts?.responseOpts);
    };

    /**
     * Update platform setting
     */
    updatePlatformSettings({ platformSettingsUpdateDto }: UpdatePlatformSettingsRequest): Observable<void>
    updatePlatformSettings({ platformSettingsUpdateDto }: UpdatePlatformSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    updatePlatformSettings({ platformSettingsUpdateDto }: UpdatePlatformSettingsRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(platformSettingsUpdateDto, 'platformSettingsUpdateDto', 'updatePlatformSettings');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/v1/settings/platform',
            method: 'PUT',
            headers,
            body: platformSettingsUpdateDto,
        }, opts?.responseOpts);
    };

}
