// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.102-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BulkActionMessageDto,
    ErrorMessageDto,
    PaginationResponseDtoTimeQualityConfigurationListDto,
    SearchFieldDataByGroupDto,
    SearchRequestDto,
    SimplifiedSigningProfileDto,
    TimeQualityConfigurationDto,
    TimeQualityConfigurationRequestDto,
} from '../models';

export interface BulkDeleteTimeQualityConfigurationsRequest {
    requestBody: Array<string>;
}

export interface CreateTimeQualityConfigurationRequest {
    timeQualityConfigurationRequestDto: TimeQualityConfigurationRequestDto;
}

export interface DeleteTimeQualityConfigurationRequest {
    uuid: string;
}

export interface GetTimeQualityConfigurationRequest {
    uuid: string;
}

export interface ListSigningProfilesForTimeQualityConfigurationRequest {
    uuid: string;
}

export interface ListTimeQualityConfigurationsRequest {
    searchRequestDto: SearchRequestDto;
}

export interface UpdateTimeQualityConfigurationRequest {
    uuid: string;
    timeQualityConfigurationRequestDto: TimeQualityConfigurationRequestDto;
}

/**
 * no description
 */
export class TimeQualityConfigurationManagementApi extends BaseAPI {
    /**
     * Delete multiple Time Quality Configurations
     */
    bulkDeleteTimeQualityConfigurations({
        requestBody,
    }: BulkDeleteTimeQualityConfigurationsRequest): Observable<Array<BulkActionMessageDto>>;
    bulkDeleteTimeQualityConfigurations(
        { requestBody }: BulkDeleteTimeQualityConfigurationsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BulkActionMessageDto>>>;
    bulkDeleteTimeQualityConfigurations(
        { requestBody }: BulkDeleteTimeQualityConfigurationsRequest,
        opts?: OperationOpts,
    ): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDeleteTimeQualityConfigurations');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>(
            {
                url: '/v1/timeQualityConfigurations',
                method: 'DELETE',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Add new Time Quality Configuration
     */
    createTimeQualityConfiguration({
        timeQualityConfigurationRequestDto,
    }: CreateTimeQualityConfigurationRequest): Observable<TimeQualityConfigurationDto>;
    createTimeQualityConfiguration(
        { timeQualityConfigurationRequestDto }: CreateTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TimeQualityConfigurationDto>>;
    createTimeQualityConfiguration(
        { timeQualityConfigurationRequestDto }: CreateTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<TimeQualityConfigurationDto | AjaxResponse<TimeQualityConfigurationDto>> {
        throwIfNullOrUndefined(timeQualityConfigurationRequestDto, 'timeQualityConfigurationRequestDto', 'createTimeQualityConfiguration');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TimeQualityConfigurationDto>(
            {
                url: '/v1/timeQualityConfigurations',
                method: 'POST',
                headers,
                body: timeQualityConfigurationRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete Time Quality Configuration
     */
    deleteTimeQualityConfiguration({ uuid }: DeleteTimeQualityConfigurationRequest): Observable<void>;
    deleteTimeQualityConfiguration(
        { uuid }: DeleteTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    deleteTimeQualityConfiguration(
        { uuid }: DeleteTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteTimeQualityConfiguration');

        return this.request<void>(
            {
                url: '/v1/timeQualityConfigurations/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Details of a Time Quality Configuration
     */
    getTimeQualityConfiguration({ uuid }: GetTimeQualityConfigurationRequest): Observable<TimeQualityConfigurationDto>;
    getTimeQualityConfiguration(
        { uuid }: GetTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TimeQualityConfigurationDto>>;
    getTimeQualityConfiguration(
        { uuid }: GetTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<TimeQualityConfigurationDto | AjaxResponse<TimeQualityConfigurationDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getTimeQualityConfiguration');

        return this.request<TimeQualityConfigurationDto>(
            {
                url: '/v1/timeQualityConfigurations/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List Signing Profiles using this Time Quality Configuration
     */
    listSigningProfilesForTimeQualityConfiguration({
        uuid,
    }: ListSigningProfilesForTimeQualityConfigurationRequest): Observable<Array<SimplifiedSigningProfileDto>>;
    listSigningProfilesForTimeQualityConfiguration(
        { uuid }: ListSigningProfilesForTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<SimplifiedSigningProfileDto>>>;
    listSigningProfilesForTimeQualityConfiguration(
        { uuid }: ListSigningProfilesForTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<Array<SimplifiedSigningProfileDto> | AjaxResponse<Array<SimplifiedSigningProfileDto>>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'listSigningProfilesForTimeQualityConfiguration');

        return this.request<Array<SimplifiedSigningProfileDto>>(
            {
                url: '/v1/timeQualityConfigurations/{uuid}/signingProfiles'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List search filters for Time Quality Configurations
     */
    listTimeQualityConfigurationSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    listTimeQualityConfigurationSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    listTimeQualityConfigurationSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/timeQualityConfigurations/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List of available Time Quality Configurations
     */
    listTimeQualityConfigurations({
        searchRequestDto,
    }: ListTimeQualityConfigurationsRequest): Observable<PaginationResponseDtoTimeQualityConfigurationListDto>;
    listTimeQualityConfigurations(
        { searchRequestDto }: ListTimeQualityConfigurationsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoTimeQualityConfigurationListDto>>;
    listTimeQualityConfigurations(
        { searchRequestDto }: ListTimeQualityConfigurationsRequest,
        opts?: OperationOpts,
    ): Observable<
        PaginationResponseDtoTimeQualityConfigurationListDto | AjaxResponse<PaginationResponseDtoTimeQualityConfigurationListDto>
    > {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listTimeQualityConfigurations');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoTimeQualityConfigurationListDto>(
            {
                url: '/v1/timeQualityConfigurations/list',
                method: 'POST',
                headers,
                body: searchRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Update Time Quality Configuration
     */
    updateTimeQualityConfiguration({
        uuid,
        timeQualityConfigurationRequestDto,
    }: UpdateTimeQualityConfigurationRequest): Observable<TimeQualityConfigurationDto>;
    updateTimeQualityConfiguration(
        { uuid, timeQualityConfigurationRequestDto }: UpdateTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TimeQualityConfigurationDto>>;
    updateTimeQualityConfiguration(
        { uuid, timeQualityConfigurationRequestDto }: UpdateTimeQualityConfigurationRequest,
        opts?: OperationOpts,
    ): Observable<TimeQualityConfigurationDto | AjaxResponse<TimeQualityConfigurationDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'updateTimeQualityConfiguration');
        throwIfNullOrUndefined(timeQualityConfigurationRequestDto, 'timeQualityConfigurationRequestDto', 'updateTimeQualityConfiguration');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TimeQualityConfigurationDto>(
            {
                url: '/v1/timeQualityConfigurations/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'PUT',
                headers,
                body: timeQualityConfigurationRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
