// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.16.3-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BulkActionMessageDto,
    ErrorMessageDto,
    PaginationResponseDtoTspConfigurationListDto,
    SearchFieldDataByGroupDto,
    SearchRequestDto,
    TspConfigurationDto,
    TspConfigurationRequestDto,
} from '../models';

export interface BulkDeleteTspConfigurationsRequest {
    requestBody: Array<string>;
}

export interface BulkDisableTspConfigurationsRequest {
    requestBody: Array<string>;
}

export interface BulkEnableTspConfigurationsRequest {
    requestBody: Array<string>;
}

export interface CreateTspConfigurationRequest {
    tspConfigurationRequestDto: TspConfigurationRequestDto;
}

export interface DeleteTspConfigurationRequest {
    uuid: string;
}

export interface DisableTspConfigurationRequest {
    uuid: string;
}

export interface EnableTspConfigurationRequest {
    uuid: string;
}

export interface GetTspConfigurationRequest {
    uuid: string;
}

export interface ListTspConfigurationsRequest {
    searchRequestDto: SearchRequestDto;
}

export interface UpdateTspConfigurationRequest {
    uuid: string;
    tspConfigurationRequestDto: TspConfigurationRequestDto;
}

/**
 * no description
 */
export class TSPConfigurationManagementApi extends BaseAPI {

    /**
     * Delete multiple TSP Configurations
     */
    bulkDeleteTspConfigurations({ requestBody }: BulkDeleteTspConfigurationsRequest): Observable<Array<BulkActionMessageDto>>
    bulkDeleteTspConfigurations({ requestBody }: BulkDeleteTspConfigurationsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<BulkActionMessageDto>>>
    bulkDeleteTspConfigurations({ requestBody }: BulkDeleteTspConfigurationsRequest, opts?: OperationOpts): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDeleteTspConfigurations');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>({
            url: '/v1/tspConfigurations',
            method: 'DELETE',
            headers,
            body: requestBody,
        }, opts?.responseOpts);
    };

    /**
     * Disable multiple TSP Configurations
     */
    bulkDisableTspConfigurations({ requestBody }: BulkDisableTspConfigurationsRequest): Observable<Array<BulkActionMessageDto>>
    bulkDisableTspConfigurations({ requestBody }: BulkDisableTspConfigurationsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<BulkActionMessageDto>>>
    bulkDisableTspConfigurations({ requestBody }: BulkDisableTspConfigurationsRequest, opts?: OperationOpts): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDisableTspConfigurations');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>({
            url: '/v1/tspConfigurations/disable',
            method: 'PATCH',
            headers,
            body: requestBody,
        }, opts?.responseOpts);
    };

    /**
     * Enable multiple TSP Configurations
     */
    bulkEnableTspConfigurations({ requestBody }: BulkEnableTspConfigurationsRequest): Observable<Array<BulkActionMessageDto>>
    bulkEnableTspConfigurations({ requestBody }: BulkEnableTspConfigurationsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<BulkActionMessageDto>>>
    bulkEnableTspConfigurations({ requestBody }: BulkEnableTspConfigurationsRequest, opts?: OperationOpts): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkEnableTspConfigurations');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>({
            url: '/v1/tspConfigurations/enable',
            method: 'PATCH',
            headers,
            body: requestBody,
        }, opts?.responseOpts);
    };

    /**
     * Add new TSP Configuration
     */
    createTspConfiguration({ tspConfigurationRequestDto }: CreateTspConfigurationRequest): Observable<TspConfigurationDto>
    createTspConfiguration({ tspConfigurationRequestDto }: CreateTspConfigurationRequest, opts?: OperationOpts): Observable<AjaxResponse<TspConfigurationDto>>
    createTspConfiguration({ tspConfigurationRequestDto }: CreateTspConfigurationRequest, opts?: OperationOpts): Observable<TspConfigurationDto | AjaxResponse<TspConfigurationDto>> {
        throwIfNullOrUndefined(tspConfigurationRequestDto, 'tspConfigurationRequestDto', 'createTspConfiguration');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TspConfigurationDto>({
            url: '/v1/tspConfigurations',
            method: 'POST',
            headers,
            body: tspConfigurationRequestDto,
        }, opts?.responseOpts);
    };

    /**
     * Delete TSP Configuration
     */
    deleteTspConfiguration({ uuid }: DeleteTspConfigurationRequest): Observable<void>
    deleteTspConfiguration({ uuid }: DeleteTspConfigurationRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    deleteTspConfiguration({ uuid }: DeleteTspConfigurationRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteTspConfiguration');

        return this.request<void>({
            url: '/v1/tspConfigurations/{uuid}'.replace('{uuid}', encodeURI(uuid)),
            method: 'DELETE',
        }, opts?.responseOpts);
    };

    /**
     * Disable TSP Configuration
     */
    disableTspConfiguration({ uuid }: DisableTspConfigurationRequest): Observable<void>
    disableTspConfiguration({ uuid }: DisableTspConfigurationRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    disableTspConfiguration({ uuid }: DisableTspConfigurationRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'disableTspConfiguration');

        return this.request<void>({
            url: '/v1/tspConfigurations/{uuid}/disable'.replace('{uuid}', encodeURI(uuid)),
            method: 'PATCH',
        }, opts?.responseOpts);
    };

    /**
     * Enable TSP Configuration
     */
    enableTspConfiguration({ uuid }: EnableTspConfigurationRequest): Observable<void>
    enableTspConfiguration({ uuid }: EnableTspConfigurationRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    enableTspConfiguration({ uuid }: EnableTspConfigurationRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'enableTspConfiguration');

        return this.request<void>({
            url: '/v1/tspConfigurations/{uuid}/enable'.replace('{uuid}', encodeURI(uuid)),
            method: 'PATCH',
        }, opts?.responseOpts);
    };

    /**
     * Details of a TSP Configuration
     */
    getTspConfiguration({ uuid }: GetTspConfigurationRequest): Observable<TspConfigurationDto>
    getTspConfiguration({ uuid }: GetTspConfigurationRequest, opts?: OperationOpts): Observable<AjaxResponse<TspConfigurationDto>>
    getTspConfiguration({ uuid }: GetTspConfigurationRequest, opts?: OperationOpts): Observable<TspConfigurationDto | AjaxResponse<TspConfigurationDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getTspConfiguration');

        return this.request<TspConfigurationDto>({
            url: '/v1/tspConfigurations/{uuid}'.replace('{uuid}', encodeURI(uuid)),
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * List search filters for TSP Configurations
     */
    listTspConfigurationSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>
    listTspConfigurationSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>
    listTspConfigurationSearchableFields(opts?: OperationOpts): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>({
            url: '/v1/tspConfigurations/search',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     * List of available TSP Configurations
     */
    listTspConfigurations({ searchRequestDto }: ListTspConfigurationsRequest): Observable<PaginationResponseDtoTspConfigurationListDto>
    listTspConfigurations({ searchRequestDto }: ListTspConfigurationsRequest, opts?: OperationOpts): Observable<AjaxResponse<PaginationResponseDtoTspConfigurationListDto>>
    listTspConfigurations({ searchRequestDto }: ListTspConfigurationsRequest, opts?: OperationOpts): Observable<PaginationResponseDtoTspConfigurationListDto | AjaxResponse<PaginationResponseDtoTspConfigurationListDto>> {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listTspConfigurations');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoTspConfigurationListDto>({
            url: '/v1/tspConfigurations/list',
            method: 'POST',
            headers,
            body: searchRequestDto,
        }, opts?.responseOpts);
    };

    /**
     * Update TSP Configuration
     */
    updateTspConfiguration({ uuid, tspConfigurationRequestDto }: UpdateTspConfigurationRequest): Observable<TspConfigurationDto>
    updateTspConfiguration({ uuid, tspConfigurationRequestDto }: UpdateTspConfigurationRequest, opts?: OperationOpts): Observable<AjaxResponse<TspConfigurationDto>>
    updateTspConfiguration({ uuid, tspConfigurationRequestDto }: UpdateTspConfigurationRequest, opts?: OperationOpts): Observable<TspConfigurationDto | AjaxResponse<TspConfigurationDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'updateTspConfiguration');
        throwIfNullOrUndefined(tspConfigurationRequestDto, 'tspConfigurationRequestDto', 'updateTspConfiguration');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TspConfigurationDto>({
            url: '/v1/tspConfigurations/{uuid}'.replace('{uuid}', encodeURI(uuid)),
            method: 'PUT',
            headers,
            body: tspConfigurationRequestDto,
        }, opts?.responseOpts);
    };

}
