// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.102-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BulkActionMessageDto,
    ErrorMessageDto,
    PaginationResponseDtoTspProfileListDto,
    SearchFieldDataByGroupDto,
    SearchRequestDto,
    TspProfileDto,
    TspProfileRequestDto,
} from '../models';

export interface BulkDeleteTspProfilesRequest {
    requestBody: Array<string>;
}

export interface BulkDisableTspProfilesRequest {
    requestBody: Array<string>;
}

export interface BulkEnableTspProfilesRequest {
    requestBody: Array<string>;
}

export interface CreateTspProfileRequest {
    tspProfileRequestDto: TspProfileRequestDto;
}

export interface DeleteTspProfileRequest {
    uuid: string;
}

export interface DisableTspProfileRequest {
    uuid: string;
}

export interface EnableTspProfileRequest {
    uuid: string;
}

export interface GetTspProfileRequest {
    uuid: string;
}

export interface ListTspProfilesRequest {
    searchRequestDto: SearchRequestDto;
}

export interface UpdateTspProfileRequest {
    uuid: string;
    tspProfileRequestDto: TspProfileRequestDto;
}

/**
 * no description
 */
export class TSPProfileManagementApi extends BaseAPI {
    /**
     * Delete multiple TSP Profiles
     */
    bulkDeleteTspProfiles({ requestBody }: BulkDeleteTspProfilesRequest): Observable<Array<BulkActionMessageDto>>;
    bulkDeleteTspProfiles(
        { requestBody }: BulkDeleteTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BulkActionMessageDto>>>;
    bulkDeleteTspProfiles(
        { requestBody }: BulkDeleteTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDeleteTspProfiles');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>(
            {
                url: '/v1/tspProfiles',
                method: 'DELETE',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Disable multiple TSP Profiles
     */
    bulkDisableTspProfiles({ requestBody }: BulkDisableTspProfilesRequest): Observable<Array<BulkActionMessageDto>>;
    bulkDisableTspProfiles(
        { requestBody }: BulkDisableTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BulkActionMessageDto>>>;
    bulkDisableTspProfiles(
        { requestBody }: BulkDisableTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDisableTspProfiles');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>(
            {
                url: '/v1/tspProfiles/disable',
                method: 'PATCH',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Enable multiple TSP Profiles
     */
    bulkEnableTspProfiles({ requestBody }: BulkEnableTspProfilesRequest): Observable<Array<BulkActionMessageDto>>;
    bulkEnableTspProfiles(
        { requestBody }: BulkEnableTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BulkActionMessageDto>>>;
    bulkEnableTspProfiles(
        { requestBody }: BulkEnableTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkEnableTspProfiles');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>(
            {
                url: '/v1/tspProfiles/enable',
                method: 'PATCH',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Add new TSP Profile
     */
    createTspProfile({ tspProfileRequestDto }: CreateTspProfileRequest): Observable<TspProfileDto>;
    createTspProfile({ tspProfileRequestDto }: CreateTspProfileRequest, opts?: OperationOpts): Observable<AjaxResponse<TspProfileDto>>;
    createTspProfile(
        { tspProfileRequestDto }: CreateTspProfileRequest,
        opts?: OperationOpts,
    ): Observable<TspProfileDto | AjaxResponse<TspProfileDto>> {
        throwIfNullOrUndefined(tspProfileRequestDto, 'tspProfileRequestDto', 'createTspProfile');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TspProfileDto>(
            {
                url: '/v1/tspProfiles',
                method: 'POST',
                headers,
                body: tspProfileRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete TSP Profile
     */
    deleteTspProfile({ uuid }: DeleteTspProfileRequest): Observable<void>;
    deleteTspProfile({ uuid }: DeleteTspProfileRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    deleteTspProfile({ uuid }: DeleteTspProfileRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteTspProfile');

        return this.request<void>(
            {
                url: '/v1/tspProfiles/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Disable TSP Profile
     */
    disableTspProfile({ uuid }: DisableTspProfileRequest): Observable<void>;
    disableTspProfile({ uuid }: DisableTspProfileRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    disableTspProfile({ uuid }: DisableTspProfileRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'disableTspProfile');

        return this.request<void>(
            {
                url: '/v1/tspProfiles/{uuid}/disable'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Enable TSP Profile
     */
    enableTspProfile({ uuid }: EnableTspProfileRequest): Observable<void>;
    enableTspProfile({ uuid }: EnableTspProfileRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    enableTspProfile({ uuid }: EnableTspProfileRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'enableTspProfile');

        return this.request<void>(
            {
                url: '/v1/tspProfiles/{uuid}/enable'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Details of a TSP Profile
     */
    getTspProfile({ uuid }: GetTspProfileRequest): Observable<TspProfileDto>;
    getTspProfile({ uuid }: GetTspProfileRequest, opts?: OperationOpts): Observable<AjaxResponse<TspProfileDto>>;
    getTspProfile({ uuid }: GetTspProfileRequest, opts?: OperationOpts): Observable<TspProfileDto | AjaxResponse<TspProfileDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getTspProfile');

        return this.request<TspProfileDto>(
            {
                url: '/v1/tspProfiles/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List search filters for TSP Profiles
     */
    listTspProfileSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    listTspProfileSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    listTspProfileSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/tspProfiles/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * List of available TSP Profiles
     */
    listTspProfiles({ searchRequestDto }: ListTspProfilesRequest): Observable<PaginationResponseDtoTspProfileListDto>;
    listTspProfiles(
        { searchRequestDto }: ListTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoTspProfileListDto>>;
    listTspProfiles(
        { searchRequestDto }: ListTspProfilesRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoTspProfileListDto | AjaxResponse<PaginationResponseDtoTspProfileListDto>> {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listTspProfiles');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoTspProfileListDto>(
            {
                url: '/v1/tspProfiles/list',
                method: 'POST',
                headers,
                body: searchRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Update TSP Profile
     */
    updateTspProfile({ uuid, tspProfileRequestDto }: UpdateTspProfileRequest): Observable<TspProfileDto>;
    updateTspProfile(
        { uuid, tspProfileRequestDto }: UpdateTspProfileRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<TspProfileDto>>;
    updateTspProfile(
        { uuid, tspProfileRequestDto }: UpdateTspProfileRequest,
        opts?: OperationOpts,
    ): Observable<TspProfileDto | AjaxResponse<TspProfileDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'updateTspProfile');
        throwIfNullOrUndefined(tspProfileRequestDto, 'tspProfileRequestDto', 'updateTspProfile');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<TspProfileDto>(
            {
                url: '/v1/tspProfiles/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'PUT',
                headers,
                body: tspProfileRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
