// tslint:disable
/**
 * CZERTAINLY Utils Service API
 * REST APIs for utility and helper function to work with certificates
 *
 * The version of the OpenAPI document: 1.0.0-SNAPSHOT
 * Contact: getinfo@czertainly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface X509CertificateExtendedData
 */
export interface X509CertificateExtendedData {
    /**
     * Subject of the X.509 certificate
     * @type {string}
     * @memberof X509CertificateExtendedData
     */
    subject: string;
    /**
     * Issuer of the X.509 certificate
     * @type {string}
     * @memberof X509CertificateExtendedData
     */
    issuer: string;
    /**
     * notBefore in epoch / unix format
     * @type {number}
     * @memberof X509CertificateExtendedData
     */
    validFrom: number;
    /**
     * notAfter in epoch / unix format
     * @type {number}
     * @memberof X509CertificateExtendedData
     */
    validTo: number;
    /**
     * Serial number of the certificate in HEX
     * @type {string}
     * @memberof X509CertificateExtendedData
     */
    serialNumber: string;
    /**
     * Version of the X.509 certificate
     * @type {number}
     * @memberof X509CertificateExtendedData
     */
    version: number;
    /**
     * Signature algorithm for the certificate
     * @type {string}
     * @memberof X509CertificateExtendedData
     */
    signatureAlgorithm: string;
    /**
     * Public key algorithm
     * @type {string}
     * @memberof X509CertificateExtendedData
     */
    algorithm: string;
    /**
     * Base64-encoded public key
     * @type {string}
     * @memberof X509CertificateExtendedData
     */
    publicKey: string;
    /**
     * List of subject alternative names
     * @type {Array<string>}
     * @memberof X509CertificateExtendedData
     */
    sans?: Array<string>;
}
