export const availableFilters = [
    {
        filterFieldSource: 'custom',
        searchFieldData: [
            {
                fieldIdentifier: 'AWS_Region|TEXT',
                fieldLabel: 'AWS_Region',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'AWS_Zone|TEXT',
                fieldLabel: 'AWS_Zone',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'AWS_accountId|TEXT',
                fieldLabel: 'AWS_accountId',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'department|STRING',
                fieldLabel: 'Department',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'string',
                value: ['IT', 'HR', 'Sales'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SecretAttribute|TEXT',
                fieldLabel: 'SecretAttribute',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'TestInt|INTEGER',
                fieldLabel: 'Test integer',
                type: 'number',
                conditions: ['EQUALS', 'NOT_EQUALS', 'GREATER', 'GREATER_OR_EQUAL', 'LESSER', 'LESSER_OR_EQUAL', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'integer',
                multiValue: false,
            },
            {
                fieldIdentifier: 'datecustom|DATE',
                fieldLabel: 'datecustom',
                type: 'date',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                attributeContentType: 'date',
                multiValue: false,
            },
            {
                fieldIdentifier: 'datetimecustom|DATETIME',
                fieldLabel: 'datetimecustom',
                type: 'date',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                attributeContentType: 'datetime',
                multiValue: false,
            },
            {
                fieldIdentifier: 'textCustomAttrExecution|TEXT',
                fieldLabel: 'textCustomAttrExecution',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'text',
                value: ['t1', 't2', 't3'],
                multiValue: true,
            },
        ],
    },
    {
        filterFieldSource: 'data',
        searchFieldData: [
            {
                fieldIdentifier: 'email|STRING',
                fieldLabel: 'Email',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
        ],
    },
    {
        filterFieldSource: 'meta',
        searchFieldData: [
            {
                fieldIdentifier: 'keystore.alias|STRING',
                fieldLabel: 'Alias',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_ca_name|STRING',
                fieldLabel: 'CA Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'certificateProfileId|STRING',
                fieldLabel: 'Certificate Profile ID',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_template_name|STRING',
                fieldLabel: 'Certificate Template Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'discoveryName|STRING',
                fieldLabel: 'Discovery Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'discoverySource|STRING',
                fieldLabel: 'Discovery Source (string)',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'discoverySource|STRING',
                fieldLabel: 'Discovery Source (string)',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'ejbcaUsername|STRING',
                fieldLabel: 'EJBCA Username',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'email|STRING',
                fieldLabel: 'Email',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'endEntityProfileId|STRING',
                fieldLabel: 'End Entity Profile ID',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_sslmateFriendlyName|STRING',
                fieldLabel: 'Friendly Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'keystore.containsKey|BOOLEAN',
                fieldLabel: 'Is Private Key Available',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'boolean',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_sslmateProblemReporting|STRING',
                fieldLabel: 'Problem Reporting',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'username|STRING',
                fieldLabel: 'Username',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
        ],
    },
    {
        filterFieldSource: 'property',
        searchFieldData: [
            {
                fieldIdentifier: 'ALT_KEY_SIZE',
                fieldLabel: 'Alternative Key Size',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [20736, 2048, 15616],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ALT_PUBLIC_KEY_ALGORITHM',
                fieldLabel: 'Alternative Public Key Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: ['MLDSA', 'ML-DSA', 'RSA'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ALT_SIGNATURE_ALGORITHM',
                fieldLabel: 'Alternative Signature Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: ['ML-DSA-65'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ARCHIVED',
                fieldLabel: 'Archived',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'CRL_VALIDATION',
                fieldLabel: 'CRL Validation',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERTIFICATE_PROTOCOL',
                fieldLabel: 'Certificate Protocol',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateProtocol',
                value: ['acme', 'cmp', 'scep'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'COMMON_NAME',
                fieldLabel: 'Common Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'COMPLIANCE_STATUS',
                fieldLabel: 'Compliance Status',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'ComplianceStatus',
                value: ['not_checked', 'ok', 'nok', 'na'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'NOT_AFTER',
                fieldLabel: 'Expires At',
                type: 'datetime',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'FINGERPRINT',
                fieldLabel: 'Fingerprint',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'GROUP_NAME',
                fieldLabel: 'Groups',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                value: [
                    'test-group-1',
                    'test-group-2',
                    'asd',
                    'AXAUX',
                    'hhh',
                    'ABCDEF',
                    '3key-info',
                    'team',
                    'Validators',
                    'example',
                    'name',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'PRIVATE_KEY',
                fieldLabel: 'Has private key',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'HYBRID_CERTIFICATE',
                fieldLabel: 'Hybrid Certificate',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'ISSUER_COMMON_NAME',
                fieldLabel: 'Issuer Common Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'ISSUERDN',
                fieldLabel: 'Issuer DN',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'ISSUER_SERIAL_NUMBER',
                fieldLabel: 'Issuer Serial Number',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'KEY_SIZE',
                fieldLabel: 'Key Size',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [3072, 239, 4096, 521, 15616, 256, 1024, 2048, 14344, 1536, 282, 192, 10496, 20736, 384],
                multiValue: true,
            },
            {
                fieldIdentifier: 'KEY_USAGE',
                fieldLabel: 'Key Usage',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    'digitalSignature',
                    'nonRepudiation',
                    'keyEncipherment',
                    'keyCertSign',
                    'cRLSign',
                    'keyAgreement',
                    'dataEncipherment',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERT_LOCATION_NAME',
                fieldLabel: 'Locations',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                value: ['lab07-myKeystore.p12'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'OCSP_VALIDATION',
                fieldLabel: 'OCSP Validation',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'OWNER',
                fieldLabel: 'Owner',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    'all-excluding-certificates',
                    'low-privilege-user',
                    'acme',
                    'permissions-test',
                    'snehal',
                    'scep',
                    'czertainly-admin',
                    'keycloak-service',
                    'roman.cinkais@3key.company',
                    'abcdef',
                    'czertainly-api-client-1',
                    'cmp',
                    'localhost',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'PRECEDING_CERTIFICATES',
                fieldLabel: 'Preceding Certificates',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                platformEnum: 'CertificateRelationType',
                value: ['renewal', 'rekey', 'replacement', 'pending'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'PUBLIC_KEY_ALGORITHM',
                fieldLabel: 'Public Key Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: ['DSA', 'DILITHIUM2', 'MLDSA', 'RSA', 'DILITHIUM5', 'ECDSA', 'FALCON-1024', 'ML-DSA', 'ML-DSA-65'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'RA_PROFILE_NAME',
                fieldLabel: 'RA Profile',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    'czertainly s mezerou',
                    'x',
                    'testRA',
                    'test-ra-cmp-01',
                    'SemikACME',
                    'KB Test',
                    'xxx',
                    'ejbca-webserver',
                    'ejbca-ml-dsa',
                    'Custom',
                    'hybridRA',
                    'czertainly',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SERIAL_NUMBER',
                fieldLabel: 'Serial Number',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SIGNATURE_ALGORITHM',
                fieldLabel: 'Signature Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    'FALCON-1024',
                    'ML-DSA-65',
                    'SHA256withECDSA',
                    'SHA512withRSAandMGF1',
                    'SHA384withRSA',
                    'SHA256withRSA',
                    'SHA1withRSA',
                    'SHA256withRSAandMGF1',
                    'DILITHIUM2',
                    'SHA512withRSA',
                    'SHA384withECDSA',
                    'DILITHIUM5',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SIGNATURE_VALIDATION',
                fieldLabel: 'Signature Validation',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERTIFICATE_STATE',
                fieldLabel: 'State',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateState',
                value: ['requested', 'rejected', 'pending_approval', 'pending_issue', 'pending_revoke', 'failed', 'issued', 'revoked'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SUBJECT_ALTERNATIVE_NAMES',
                fieldLabel: 'Subject Alternative Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SUBJECTDN',
                fieldLabel: 'Subject DN',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SUBJECT_TYPE',
                fieldLabel: 'Subject Type',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateSubjectType',
                value: ['endEntity', 'selfSignedEndEntity', 'intermediateCa', 'rootCa'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SUCCEEDING_CERTIFICATES',
                fieldLabel: 'Succeeding Certificates',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                platformEnum: 'CertificateRelationType',
                value: ['renewal', 'rekey', 'replacement', 'pending'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'TRUSTED_CA',
                fieldLabel: 'Trusted CA',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'NOT_BEFORE',
                fieldLabel: 'Valid From',
                type: 'datetime',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'CERTIFICATE_VALIDATION_STATUS',
                fieldLabel: 'Validation status',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
        ],
    },
];
