export const mockAvailableFilters = [
    {
        filterFieldSource: 'data',
        searchFieldData: [
            {
                fieldIdentifier: 'dataField|TEXT',
                fieldLabel: 'Data Field',
                type: 'string',
                conditions: ['CONTAINS', 'NOT_CONTAINS', 'EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'text',
                multiValue: false,
            },
        ],
    },
    {
        filterFieldSource: 'meta',
        searchFieldData: [
            {
                fieldIdentifier: 'metaField|TEXT',
                fieldLabel: 'Meta Field',
                type: 'string',
                conditions: ['CONTAINS', 'NOT_CONTAINS', 'EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'username|STRING',
                fieldLabel: 'Username',
                type: 'string',
                conditions: ['CONTAINS', 'NOT_CONTAINS', 'EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'text',
                multiValue: false,
            },
        ],
    },
    {
        filterFieldSource: 'custom',
        searchFieldData: [
            {
                fieldIdentifier: 'AWS_Region|TEXT',
                fieldLabel: 'AWS_Region',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'AWS_Zone|TEXT',
                fieldLabel: 'AWS_Zone',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'AWS_accountId|TEXT',
                fieldLabel: 'AWS_accountId',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'department|STRING',
                fieldLabel: 'Department',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'string',
                value: ['IT', 'HR', 'Sales'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SecretAttribute|TEXT',
                fieldLabel: 'SecretAttribute',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'TestInt|INTEGER',
                fieldLabel: 'Test integer',
                type: 'number',
                conditions: ['EQUALS', 'NOT_EQUALS', 'GREATER', 'GREATER_OR_EQUAL', 'LESSER', 'LESSER_OR_EQUAL', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'integer',
                multiValue: false,
            },
            {
                fieldIdentifier: 'datecustom|DATE',
                fieldLabel: 'datecustom',
                type: 'date',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                attributeContentType: 'date',
                multiValue: false,
            },
            {
                fieldIdentifier: 'datetimecustom|DATETIME',
                fieldLabel: 'datetimecustom',
                type: 'date',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                attributeContentType: 'datetime',
                multiValue: false,
            },
            {
                fieldIdentifier: 'textCustomAttrExecution|TEXT',
                fieldLabel: 'textCustomAttrExecution',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'text',
                value: ['t1', 't2', 't3'],
                multiValue: true,
            },
        ],
    },
    {
        filterFieldSource: 'data',
        searchFieldData: [
            {
                fieldIdentifier: 'email|STRING',
                fieldLabel: 'Email',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
        ],
    },
    {
        filterFieldSource: 'meta',
        searchFieldData: [
            {
                fieldIdentifier: 'keystore.alias|STRING',
                fieldLabel: 'Alias',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_ca_name|STRING',
                fieldLabel: 'CA Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'certificateProfileId|STRING',
                fieldLabel: 'Certificate Profile ID',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_template_name|STRING',
                fieldLabel: 'Certificate Template Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'discoveryName|STRING',
                fieldLabel: 'Discovery Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'discoverySource|STRING',
                fieldLabel: 'Discovery Source (string)',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'discoverySource|STRING',
                fieldLabel: 'Discovery Source (string)',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'ejbcaUsername|STRING',
                fieldLabel: 'EJBCA Username',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'email|STRING',
                fieldLabel: 'Email',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'endEntityProfileId|STRING',
                fieldLabel: 'End Entity Profile ID',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_sslmateFriendlyName|STRING',
                fieldLabel: 'Friendly Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'keystore.containsKey|BOOLEAN',
                fieldLabel: 'Is Private Key Available',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'boolean',
                multiValue: false,
            },
            {
                fieldIdentifier: 'metadata_sslmateProblemReporting|STRING',
                fieldLabel: 'Problem Reporting',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
            {
                fieldIdentifier: 'username|STRING',
                fieldLabel: 'Username',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                attributeContentType: 'string',
                multiValue: false,
            },
        ],
    },
    {
        filterFieldSource: 'property',
        searchFieldData: [
            {
                fieldIdentifier: 'COMMON_NAME',
                fieldLabel: 'Common Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SERIAL_NUMBER',
                fieldLabel: 'Serial Number',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'RA_PROFILE_NAME',
                fieldLabel: 'RA Profile',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    {
                        uuid: 'f1911baa-ece8-4928-a147-a71f7ddce24c',
                        name: 'czertainly s mezerou',
                    },
                    {
                        uuid: '019b573e-8b0d-41ea-9f22-f4a9bf6e8209',
                        name: 'x',
                    },
                    {
                        uuid: '31682b51-a0c7-4248-897b-5f5a8a9fadb2',
                        name: 'testRA',
                    },
                    {
                        uuid: '65c15f62-9b26-467b-9baa-18c7a8ff64a9',
                        name: 'test-ra-cmp-01',
                    },
                    {
                        uuid: '0be45e19-7392-4edf-9ac7-ecd0f9a7c7c0',
                        name: 'SemikACME',
                    },
                    {
                        uuid: 'f58ef973-5c3c-4dcf-9157-e3754f0c8ebd',
                        name: 'KB Test',
                    },
                    {
                        uuid: '808f1f9f-8807-409a-a35f-d8e594bdcd53',
                        name: 'xxx',
                    },
                    {
                        uuid: '3c10810d-268d-4999-ac56-711b394b8928',
                        name: 'ejbca-webserver',
                    },
                    {
                        uuid: '632674ac-62bb-4e57-b5c4-f75bb1d4a574',
                        name: 'ejbca-ml-dsa',
                    },
                    {
                        uuid: 'f0c0ae90-010f-4fde-91f6-7be1d9a3277e',
                        name: 'hybridRA',
                    },
                    {
                        uuid: '0bddee3a-8206-4a1a-a5ec-ee0d25445ab3',
                        name: 'czertainly',
                    },
                    {
                        uuid: 'c08e64f5-a98b-49df-908d-b3b26f50c145',
                        name: 'Custom',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERTIFICATE_TYPE',
                fieldLabel: 'Type',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateType',
                value: ['X.509', 'SSH'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERTIFICATE_STATE',
                fieldLabel: 'State',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateState',
                value: ['requested', 'rejected', 'pending_approval', 'pending_issue', 'pending_revoke', 'failed', 'issued', 'revoked'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERTIFICATE_VALIDATION_STATUS',
                fieldLabel: 'Validation status',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'COMPLIANCE_STATUS',
                fieldLabel: 'Compliance Status',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'ComplianceStatus',
                value: ['not_checked', 'ok', 'nok', 'na', 'failed'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'GROUP_NAME',
                fieldLabel: 'Groups',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                value: [
                    {
                        uuid: 'b9f33da1-595d-4747-a30b-b381700046ce',
                        name: 'test-group-1',
                    },
                    {
                        uuid: '49133b3e-149b-49ae-a6c7-fe8041f7cc82',
                        name: 'test-group-2',
                    },
                    {
                        uuid: 'd57651f4-a5ce-4155-b7aa-be23988a8f57',
                        name: 'asd',
                    },
                    {
                        uuid: '4d7a4ea7-e80d-4a59-9146-7072262c29ff',
                        name: 'AXAUX',
                    },
                    {
                        uuid: '52c2d45a-d534-4dd9-8410-df75020b5092',
                        name: 'hhh',
                    },
                    {
                        uuid: '1fa64e9a-1a34-4e87-a7dc-4ed55e3021a5',
                        name: 'ABCDEF',
                    },
                    {
                        uuid: '03af02ef-cdac-4943-b8d6-8e55d3466fe8',
                        name: '3key-info',
                    },
                    {
                        uuid: '600b642e-13d3-4a5c-859e-4dd347179a51',
                        name: 'team',
                    },
                    {
                        uuid: '1be2bc02-016b-4eee-9343-b865cedf42f6',
                        name: 'Validators',
                    },
                    {
                        uuid: '446194e4-9acd-47b6-bfc0-bfaa58392cd4',
                        name: 'example',
                    },
                    {
                        uuid: '254ae0ef-23e9-4451-b638-e554de59bca9',
                        name: 'name',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CERT_LOCATION_NAME',
                fieldLabel: 'Locations',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                value: [
                    {
                        uuid: '6f19a7c6-e72e-4b0f-a4b0-6302570e3185',
                        name: 'lab07-myKeystore.p12',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'OWNER',
                fieldLabel: 'Owner',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    {
                        uuid: '0d7e81d1-a5e0-4dd5-ac72-3c5b0a67dca6',
                        name: 'all-excluding-certificates',
                    },
                    {
                        uuid: '257779ee-ecad-448f-9abf-83b332b75568',
                        name: 'low-privilege-user',
                    },
                    {
                        uuid: '30408964-31f4-435d-b970-29013b1e147d',
                        name: 'acme',
                    },
                    {
                        uuid: '31df4dc8-fdbb-437a-af48-6bc4df8d1688',
                        name: 'permissions-test',
                    },
                    {
                        uuid: '36980a7c-42bd-4a82-855c-01d5f33dca61',
                        name: 'snehal',
                    },
                    {
                        uuid: '56aa8332-1153-4e8f-bb43-46f1d6ef7f86',
                        name: 'scep',
                    },
                    {
                        uuid: '5fa60bbf-a76c-423e-a701-07f30f3f7450',
                        name: 'czertainly-admin',
                    },
                    {
                        uuid: '65003f10-9bd4-4aaa-b09a-e9ab06c89dc3',
                        name: 'keycloak-service',
                    },
                    {
                        uuid: '68668082-e53a-48ca-9942-6f93bf4fbaae',
                        name: 'roman.cinkais@3key.company',
                    },
                    {
                        uuid: '7043acb4-d653-4fa5-872b-c530dcf4c221',
                        name: 'abcdef',
                    },
                    {
                        uuid: '92209c3f-7086-452f-a6d2-19b4f0a53a61',
                        name: 'czertainly-api-client-1',
                    },
                    {
                        uuid: 'acbc9829-612b-4cb2-a129-bdcd7ece54d2',
                        name: 'cmp',
                    },
                    {
                        uuid: 'b682b20b-92ce-4e17-84f1-4d6a21e0ab91',
                        name: 'test-delete',
                    },
                    {
                        uuid: 'c63422e1-23b0-42e8-8a70-a1a7669df073',
                        name: 'jakub',
                    },
                    {
                        uuid: 'd5811d92-054b-4660-bdbb-eedf93a338ec',
                        name: 'localhost',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ISSUER_COMMON_NAME',
                fieldLabel: 'Issuer Common Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SIGNATURE_ALGORITHM',
                fieldLabel: 'Signature Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    'FALCON-1024',
                    'ML-DSA-65',
                    'SHA512withRSAandMGF1',
                    'SHA256withECDSA',
                    'SHA384withRSA',
                    'SHA256withRSA',
                    'SHA256withRSAandMGF1',
                    'SHA1withRSA',
                    'DILITHIUM2',
                    'SHA512withRSA',
                    'SHA384withECDSA',
                    'DILITHIUM5',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ALT_SIGNATURE_ALGORITHM',
                fieldLabel: 'Alternative Signature Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: ['ML-DSA-65'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'FINGERPRINT',
                fieldLabel: 'Fingerprint',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'NOT_AFTER',
                fieldLabel: 'Expires At',
                type: 'datetime',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'NOT_BEFORE',
                fieldLabel: 'Valid From',
                type: 'datetime',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'GREATER',
                    'GREATER_OR_EQUAL',
                    'LESSER',
                    'LESSER_OR_EQUAL',
                    'EMPTY',
                    'NOT_EMPTY',
                    'IN_NEXT',
                    'IN_PAST',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'PUBLIC_KEY_ALGORITHM',
                fieldLabel: 'Public Key Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: ['DSA', 'MLDSA', 'DILITHIUM2', 'RSA', 'DILITHIUM5', 'ECDSA', 'FALCON-1024', 'ML-DSA-65', 'ML-DSA'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ALT_PUBLIC_KEY_ALGORITHM',
                fieldLabel: 'Alternative Public Key Algorithm',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: ['MLDSA', 'RSA', 'ML-DSA'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'KEY_SIZE',
                fieldLabel: 'Key Size',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [3072, 4096, 521, 15616, 8192, 256, 1024, 2048, 14344, 1536, 282, 192, 10496, 20736, 384],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ALT_KEY_SIZE',
                fieldLabel: 'Alternative Key Size',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [20736, 15616, 2048],
                multiValue: true,
            },
            {
                fieldIdentifier: 'KEY_USAGE',
                fieldLabel: 'Key Usage',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateKeyUsage',
                value: [
                    'digitalSignature',
                    'nonRepudiation',
                    'keyEncipherment',
                    'dataEncipherment',
                    'keyAgreement',
                    'keyCertSign',
                    'cRLSign',
                    'encipherOnly',
                    'decipherOnly',
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SUBJECT_TYPE',
                fieldLabel: 'Subject Type',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateSubjectType',
                value: ['endEntity', 'selfSignedEndEntity', 'intermediateCa', 'rootCa'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SUBJECT_ALTERNATIVE_NAMES',
                fieldLabel: 'Subject Alternative Name',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SUBJECTDN',
                fieldLabel: 'Subject DN',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'ISSUERDN',
                fieldLabel: 'Issuer DN',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'ISSUER_SERIAL_NUMBER',
                fieldLabel: 'Issuer Serial Number',
                type: 'string',
                conditions: [
                    'CONTAINS',
                    'NOT_CONTAINS',
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'STARTS_WITH',
                    'ENDS_WITH',
                    'MATCHES',
                    'NOT_MATCHES',
                ],
                multiValue: false,
            },
            {
                fieldIdentifier: 'OCSP_VALIDATION',
                fieldLabel: 'OCSP Validation',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CRL_VALIDATION',
                fieldLabel: 'CRL Validation',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SIGNATURE_VALIDATION',
                fieldLabel: 'Signature Validation',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateValidationStatus',
                value: ['not_checked', 'failed', 'inactive', 'invalid', 'valid', 'revoked', 'expiring', 'expired'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'PRIVATE_KEY',
                fieldLabel: 'Has private key',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'TRUSTED_CA',
                fieldLabel: 'Trusted CA',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'CERTIFICATE_PROTOCOL',
                fieldLabel: 'Certificate Protocol',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                platformEnum: 'CertificateProtocol',
                value: ['acme', 'scep', 'cmp'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'HYBRID_CERTIFICATE',
                fieldLabel: 'Hybrid Certificate',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'ARCHIVED',
                fieldLabel: 'Archived',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                multiValue: false,
            },
            {
                fieldIdentifier: 'SUCCEEDING_CERTIFICATES',
                fieldLabel: 'Succeeding Certificates',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                platformEnum: 'CertificateRelationType',
                value: ['renewal', 'rekey', 'replacement', 'pending'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'PRECEDING_CERTIFICATES',
                fieldLabel: 'Preceding Certificates',
                type: 'list',
                conditions: [
                    'EQUALS',
                    'NOT_EQUALS',
                    'EMPTY',
                    'NOT_EMPTY',
                    'COUNT_EQUAL',
                    'COUNT_NOT_EQUAL',
                    'COUNT_GREATER_THAN',
                    'COUNT_LESS_THAN',
                ],
                platformEnum: 'CertificateRelationType',
                value: ['renewal', 'rekey', 'replacement', 'pending'],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ACME_PROFILE',
                fieldLabel: 'ACME Profile',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    {
                        uuid: '8cefd24a-b3f3-40fd-a2b8-8f41e9626a7c',
                        name: 'test-acme-profile-02',
                    },
                    {
                        uuid: 'd86313a6-5af7-4edb-a12a-fbbdd36b7e66',
                        name: 'test-acme-profile-03',
                    },
                    {
                        uuid: '0c255a9e-008e-4ac8-81e8-0f047282ba2f',
                        name: 'SemikACME_at_lab02',
                    },
                    {
                        uuid: '33e6ca5d-58aa-496c-9eeb-05f2b58c18b3',
                        name: 'Custom-attribute',
                    },
                    {
                        uuid: '820355b0-38ab-46ec-a7f9-25a2e6d9da37',
                        name: 'test_Vlad',
                    },
                    {
                        uuid: '761ff879-834a-4d2e-9257-f01d01911206',
                        name: 'test2',
                    },
                    {
                        uuid: '9281dd8c-fda0-4f7e-bebd-23c41681fe49',
                        name: 'test3',
                    },
                    {
                        uuid: '0335b906-5a46-4051-8b74-05a41dbbc266',
                        name: 'MyTest',
                    },
                    {
                        uuid: '70c83966-9b51-42e6-b10e-e84c943257cc',
                        name: 'test-acme-profile-01',
                    },
                    {
                        uuid: 'aa30cf71-4bfe-480f-93ec-327077ac8e8d',
                        name: 'SemikACME',
                    },
                    {
                        uuid: '7b875514-1e55-4a66-8f5d-7c756adc2e40',
                        name: 'TSTSSTTS',
                    },
                    {
                        uuid: '91df91d9-49f8-4e5c-a02f-9cea226a23a9',
                        name: 'test11',
                    },
                    {
                        uuid: 'ef63b043-47d3-4a0d-abd6-c5c512369921',
                        name: 'test222',
                    },
                    {
                        uuid: '542416a6-d478-4884-9176-1b3f522d2691',
                        name: 'associations',
                    },
                    {
                        uuid: '60545b1f-92f8-40e4-b5bf-5e3cd17ffea6',
                        name: 'test111',
                    },
                    {
                        uuid: 'e7dfe5ea-8cb8-4c8f-bf8f-7f3d1eba83a3',
                        name: 'Custom',
                    },
                    {
                        uuid: '85ca9744-7189-479c-b450-540434f0ec1f',
                        name: 'test-perf',
                    },
                    {
                        uuid: '9433e997-520e-4b03-b7f6-07d0eeeef91e',
                        name: 'test-1',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'SCEP_PROFILE',
                fieldLabel: 'SCEP Profile',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    {
                        uuid: '34c90c64-ce93-4a81-9ca5-cf029635c6af',
                        name: 'test',
                    },
                    {
                        uuid: '8bdf0736-9d6d-4f74-b85a-85ed8c7f451b',
                        name: 'test2',
                    },
                    {
                        uuid: '5ec76a68-62fd-414e-b38b-c8c7cdcf5ed7',
                        name: 'test3',
                    },
                    {
                        uuid: '6e074612-9224-4420-ae7e-601f911c086c',
                        name: 'test222',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'CMP_PROFILE',
                fieldLabel: 'CMP Profile',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    {
                        uuid: 'ddee87fc-6685-43c8-bd87-e7c4654bc4f1',
                        name: 'test-cmp-profile-01',
                    },
                    {
                        uuid: 'd0b750ab-5431-4e4d-abf8-e3904eb95292',
                        name: 'test2',
                    },
                    {
                        uuid: 'a7a90bbf-7ce7-49f1-803b-e60d3abf4db7',
                        name: 'test',
                    },
                    {
                        uuid: 'ebbb3723-d284-4c53-9f7e-a4e648f5ca12',
                        name: 'test12222',
                    },
                    {
                        uuid: '94720dc8-6d94-488b-9949-5dac0485c375',
                        name: 'CMP-CZERTAINLY',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'ACME_ACCOUNT',
                fieldLabel: 'ACME Account',
                type: 'list',
                conditions: ['EQUALS', 'NOT_EQUALS', 'EMPTY', 'NOT_EMPTY'],
                value: [
                    {
                        uuid: 'dee3c5b7-d591-498b-aa34-1383ad7c9332',
                        name: 'HygEeKyUeSw',
                    },
                    {
                        uuid: '7ce64d41-8325-4301-9a90-aaf2b3110f2f',
                        name: 'rcyXkCYITDs',
                    },
                    {
                        uuid: '0786fed2-a4b6-4e16-a9c6-79ab626c0779',
                        name: 'ceWdSAyf8cA',
                    },
                    {
                        uuid: '1e598168-823b-4c6c-be0b-371a55672cab',
                        name: 'nYpKsjFXYvo',
                    },
                    {
                        uuid: 'fbe17fc4-5fb7-4a4e-b4e7-9ef7611d68ad',
                        name: 'C_YVhEffhcQ',
                    },
                    {
                        uuid: '01e0871d-f956-49a7-b70a-285f9bb3af61',
                        name: 'ZcyFhrsH3a8',
                    },
                    {
                        uuid: '398cb72c-5c49-4af5-a4f7-f54922021d37',
                        name: 'WkQE9D6bLEE',
                    },
                    {
                        uuid: 'a5e0dedf-3ab3-4ca8-980f-6d9a81fd9ad6',
                        name: '8Bro8JASdSg',
                    },
                    {
                        uuid: '7ab6c2ba-adb8-4b02-968e-7ff0c827f2cf',
                        name: 'CuahMi9jxiE',
                    },
                    {
                        uuid: '6a106c3a-4ba9-4856-9aa4-7438545a153f',
                        name: 'cWL6CmFhGJQ',
                    },
                    {
                        uuid: '4e702baf-0f07-4d53-9c4e-f968cd874974',
                        name: 'tR2j8zTxDQo',
                    },
                    {
                        uuid: 'abddb4ad-5848-4425-ac6e-938d90bcc18f',
                        name: 'MXotw9s2hy8',
                    },
                ],
                multiValue: true,
            },
            {
                fieldIdentifier: 'isActive|BOOLEAN',
                fieldLabel: 'Is Active',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'boolean',
                multiValue: false,
            },
            {
                fieldIdentifier: 'isEnabled|BOOLEAN',
                fieldLabel: 'Is Enabled',
                type: 'boolean',
                conditions: ['EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'boolean',
                multiValue: false,
            },
            {
                fieldIdentifier: 'createdDate|DATE',
                fieldLabel: 'Created Date',
                type: 'date',
                conditions: ['EQUALS', 'NOT_EQUALS', 'GREATER_THAN', 'LESS_THAN'],
                attributeContentType: 'date',
                multiValue: false,
            },
            {
                fieldIdentifier: 'lastModified|DATETIME',
                fieldLabel: 'Last Modified',
                type: 'datetime',
                conditions: ['EQUALS', 'NOT_EQUALS', 'GREATER_THAN', 'LESS_THAN'],
                attributeContentType: 'datetime',
                multiValue: false,
            },
            {
                fieldIdentifier: 'status|ENUM',
                fieldLabel: 'Status',
                type: 'enum',
                conditions: ['EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'text',
                platformEnum: 'StatusEnum',
                multiValue: false,
            },
            {
                fieldIdentifier: 'user|OBJECT',
                fieldLabel: 'User',
                type: 'object',
                conditions: ['EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'emptyField|TEXT',
                fieldLabel: 'Empty Field',
                type: 'string',
                conditions: ['EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'undefinedField|TEXT',
                fieldLabel: 'Undefined Field',
                type: 'string',
                conditions: ['EMPTY', 'NOT_EMPTY'],
                attributeContentType: 'text',
                multiValue: false,
            },
            {
                fieldIdentifier: 'customField|TEXT',
                fieldLabel: 'Custom Field',
                type: 'string',
                conditions: ['CONTAINS', 'NOT_CONTAINS', 'EQUALS', 'NOT_EQUALS'],
                attributeContentType: 'text',
                multiValue: false,
            },
        ],
    },
];
