name: Check PR
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Test build
        run: |
          npm ci
          npm run lint
          npm run build

      # Package up PR context for downstream workflow_run
      - name: Prepare PR context artifact
        run: |
          cat > pr-context.json <<'JSON'
          {
            "pr_number": "${{ github.event.pull_request.number }}",
            "head_sha":  "${{ github.event.pull_request.head.sha }}",
            "head_repo": "${{ github.event.pull_request.head.repo.full_name }}",
            "head_branch": "${{ github.event.pull_request.head.ref }}",
            "base_ref": "${{ github.event.pull_request.base.ref }}"
          }
          JSON
          cat pr-context.json

      - name: Upload PR context
        uses: actions/upload-artifact@v4
        with:
          name: pr-context
          path: pr-context.json
          retention-days: 1
          if-no-files-found: error
