name: Check PR
on:
  pull_request:
    branches: [ main ]

# Needed so this workflow can start another workflow
permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Test build
        run: |
          npm ci
          npm run lint
          npm run build

      # Dispatch the Sonar workflow with full PR context
      - name: Kick off Sonar
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const workflow_id = 'sonar.yml';
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.base.ref,
              workflow_id,
              inputs: {
                pr_number: String(pr.number),
                head_sha: pr.head.sha,
                head_repo: pr.head.repo.full_name,
                head_branch: pr.head.ref,
                base_ref: pr.base.ref
              },
            });
