name: Run Cypress Component Tests

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
  workflow_dispatch:

jobs:

  install:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build
        run: |
          npm install
          npm run build
        env:
          CI: false

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-ubuntu
          if-no-files-found: error
          path: build

#  install-windows:
#    runs-on: windows-2022
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20.x
#
#      - name: Build
#        run: |
#          npm install
#          npm run build
#        env:
#          CI: false
#
#      - name: Cypress install
#        uses: cypress-io/github-action@v6
#        with:
#          runTests: false
#
#      # report machine parameters
#      - run: yarn cypress info
#      - run: node --version
#      - run: node -p 'os.cpus()'
#
#      - name: Save build folder
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-windows
#          if-no-files-found: error
#          path: build

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    needs: install
    #strategy:
      # don't fail the entire matrix on failure
      #fail-fast: false
      #matrix:
        # run copies of the current job in parallel
        #containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu
          path: build

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          #record: true
          #parallel: true
          #group: "UI - Chrome"
          component: true

  ui-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    needs: install
    #strategy:
      # don't fail the entire matrix on failure
      #fail-fast: false
      #matrix:
        # run copies of the current job in parallel
        #containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu
          path: build

      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: firefox
          #record: true
          #parallel: true
          #group: "UI - Firefox"
          component: true

  ui-edge-tests:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    needs: install
      #strategy:
      # don't fail the entire matrix on failure
      #fail-fast: false
      #matrix:
    # run copies of the current job in parallel
    #containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folders
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu
          path: build

      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: edge
          #record: true
          #parallel: true
          #group: "UI - Firefox"
          component: true

#  ui-windows-tests:
#    timeout-minutes: 40
#    runs-on: windows-2022
#    needs: install-windows
#    #strategy:
#      # don't fail the entire matrix on failure
#      #fail-fast: false
#      #matrix:
#        # run copies of the current job in parallel
#        #containers: [ 1, 2, 3 ]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: "18.16.0"
#
#      - name: Download the build folders
#        uses: actions/download-artifact@v4
#        with:
#          name: build-windows
#          path: build
#
#      - name: "UI Tests - Electron - Windows"
#        uses: cypress-io/github-action@v6
#        with:
#          start: npm start
#          #record: true
#          #parallel: true
#          #group: "UI - Electron - Windows"
#          component: true
